from __future__ import annotations

from copy import deepcopy
from typing import Any


DEFAULT_AVAILABILITY = {
    "status": "unknown",
    "confidence": "low",
    "evidence_probe": None,
    "evidence_artifact": None,
    "blocked_reason": {"category": None, "detail": None},
    "partial_reason": None,
    "last_checked_at": None,
}


def _field(
    *,
    profile: str,
    name: str,
    meaning: str,
    layer: str,
    field_type: str,
    unit: str,
    required_for_p0: bool,
    sampling_mode: str,
    measurement_source: str,
    expected_tool: str,
    permission_need: str,
    collection_overhead: str,
    expected_artifact: str,
    join_key: list[str],
    time_base: str,
    validation_method: str,
    acceptance_rule: str,
    fallback: str,
    notes: str = "",
) -> dict[str, Any]:
    return {
        "name": name,
        "profile": profile,
        "meaning": meaning,
        "layer": layer,
        "field_type": field_type,
        "unit": unit,
        "required_for_p0": required_for_p0,
        "sampling_mode": sampling_mode,
        "measurement_source": measurement_source,
        "expected_tool": expected_tool,
        "permission_need": permission_need,
        "collection_overhead": collection_overhead,
        "expected_artifact": expected_artifact,
        "join_key": list(join_key),
        "time_base": time_base,
        "availability": deepcopy(DEFAULT_AVAILABILITY),
        "validation_method": validation_method,
        "acceptance_rule": acceptance_rule,
        "fallback": fallback,
        "notes": notes,
    }


def _profile_fields(
    profile: str,
    layer: str,
    names: list[tuple[str, str, str, str]],
    *,
    required_for_p0: bool,
    sampling_mode: str,
    measurement_source: str,
    expected_tool: str,
    permission_need: str,
    collection_overhead: str,
    expected_artifact: str,
    join_key: list[str],
    time_base: str,
    validation_method: str,
    acceptance_rule: str,
    fallback: str,
) -> list[dict[str, Any]]:
    return [
        _field(
            profile=profile,
            name=name,
            meaning=meaning,
            layer=layer,
            field_type=field_type,
            unit=unit,
            required_for_p0=required_for_p0,
            sampling_mode=sampling_mode,
            measurement_source=measurement_source,
            expected_tool=expected_tool,
            permission_need=permission_need,
            collection_overhead=collection_overhead,
            expected_artifact=expected_artifact,
            join_key=join_key,
            time_base=time_base,
            validation_method=validation_method,
            acceptance_rule=acceptance_rule,
            fallback=fallback,
        )
        for name, meaning, field_type, unit in names
    ]


def build_field_catalog() -> list[dict[str, Any]]:
    fields: list[dict[str, Any]] = []

    fields.extend(_profile_fields(
        "server_observability_profile",
        "server",
        [
            ("os_name", "operating system name", "inventory", "text"),
            ("kernel_version", "kernel version", "inventory", "text"),
            ("cann_version", "CANN version", "inventory", "text"),
            ("driver_version", "Ascend driver version", "inventory", "text"),
            ("firmware_version", "device firmware version", "inventory", "text"),
            ("torch_npu_version", "torch-npu version", "inventory", "text"),
            ("mindie_version", "MindIE version", "inventory", "text"),
            ("vllm_ascend_version", "vLLM-Ascend version", "inventory", "text"),
            ("container_privileged", "whether current container is privileged", "inventory", "bool"),
            ("visible_npu_count", "number of visible NPUs", "counter", "count"),
            ("npu_smi_available", "whether npu-smi is callable", "inventory", "bool"),
            ("cann_profiler_available", "whether CANN profiler is callable", "inventory", "bool"),
            ("perf_available", "whether perf is callable", "inventory", "bool"),
            ("ebpf_available", "whether bpftrace is callable", "inventory", "bool"),
            ("fio_available", "whether fio is callable", "inventory", "bool"),
            ("numa_available", "whether numactl topology inventory is callable", "inventory", "bool"),
            ("container_cgroup_readable", "whether container cgroup context is readable", "inventory", "bool"),
        ],
        required_for_p0=True,
        sampling_mode="one_shot",
        measurement_source="host and container inventory commands",
        expected_tool="uname, python, npu-smi, container runtime metadata",
        permission_need="shell_access",
        collection_overhead="low",
        expected_artifact="manifest.yaml",
        join_key=["profile_run_id"],
        time_base="host_wall_clock",
        validation_method="compare command outputs with manifest fields",
        acceptance_rule="measurable if command returns a non-empty value or explicit not_applicable",
        fallback="record unknown with command failure evidence",
    ))

    fields.extend(_profile_fields(
        "request_runtime_profile",
        "runtime",
        [
            ("arrival_time_ns", "request arrival timestamp", "event", "ns"),
            ("enqueue_time_ns", "request enqueue timestamp", "event", "ns"),
            ("dequeue_time_ns", "request dequeue timestamp", "event", "ns"),
            ("queue_wait_us", "request queue wait duration", "metric", "us"),
            ("admission_decision", "request admission decision", "event", "text"),
            ("batch_id", "runtime batch identifier", "event", "text"),
            ("batch_size", "runtime batch size", "counter", "count"),
            ("prefill_start_ns", "prefill start timestamp", "event", "ns"),
            ("prefill_end_ns", "prefill end timestamp", "event", "ns"),
            ("decode_step_start_ns", "decode step start timestamp", "event", "ns"),
            ("decode_step_end_ns", "decode step end timestamp", "event", "ns"),
            ("sampling_end_ns", "sampling end timestamp", "event", "ns"),
            ("jct_us", "job completion time", "metric", "us"),
        ],
        required_for_p0=True,
        sampling_mode="per_request",
        measurement_source="runtime request log or wrapper log",
        expected_tool="vLLM/MindIE log hook or wrapper logger",
        permission_need="app_log_access",
        collection_overhead="low",
        expected_artifact="runtime_queue_trace.jsonl",
        join_key=["trace_id", "request_id", "phase"],
        time_base="host_monotonic_ns",
        validation_method="run synthetic single request and verify monotonic timestamps",
        acceptance_rule="measurable if non-null for at least 95 percent of requests",
        fallback="wrapper-level request timestamps",
    ))

    fields.extend(_profile_fields(
        "scheduler_policy_profile",
        "runtime",
        [
            ("policy_name", "scheduler or cache policy name", "event", "text"),
            ("why_this_device", "reason device was selected", "event", "text"),
            ("why_prefetch", "reason prefetch was issued", "event", "text"),
            ("why_evict", "reason object was evicted", "event", "text"),
            ("why_recompute", "reason recompute was selected", "event", "text"),
            ("cache_allocation_event", "cache allocation event", "event", "text"),
            ("cache_free_event", "cache free event", "event", "text"),
            ("pin_unpin_event", "pin or unpin event", "event", "text"),
            ("ttl_expiry_event", "TTL expiry event", "event", "text"),
            ("backpressure_event", "backpressure event", "event", "text"),
            ("reject_reason", "request rejection reason", "event", "text"),
        ],
        required_for_p0=False,
        sampling_mode="per_request",
        measurement_source="runtime decision log",
        expected_tool="runtime hook or wrapper logger",
        permission_need="framework_hook",
        collection_overhead="medium",
        expected_artifact="runtime_queue_trace.jsonl",
        join_key=["trace_id", "request_id", "phase"],
        time_base="host_monotonic_ns",
        validation_method="verify decisions align with synthetic queue and cache actions",
        acceptance_rule="partial if decision exists at request granularity without object granularity",
        fallback="record unavailable framework hook gap",
    ))

    fields.extend(_profile_fields(
        "operator_timeline_profile",
        "operator",
        [
            ("layer_id", "model layer identifier", "event", "count"),
            ("op_name", "framework operator name", "event", "text"),
            ("kernel_name", "device kernel name", "event", "text"),
            ("cann_op_name", "CANN operator name", "event", "text"),
            ("input_shape", "operator input shape", "event", "text"),
            ("dtype", "operator dtype", "event", "text"),
            ("tiling_id", "tiling identifier", "event", "text"),
            ("launch_overhead_us", "kernel launch overhead", "metric", "us"),
            ("kernel_duration_us", "kernel duration", "metric", "us"),
            ("stream_id", "device stream identifier", "event", "text"),
            ("graph_compile_us", "graph compile duration", "metric", "us"),
            ("graph_cache_hit", "graph cache hit flag", "event", "bool"),
            ("dynamic_shape_fallback", "dynamic shape fallback flag", "event", "bool"),
        ],
        required_for_p0=True,
        sampling_mode="per_layer",
        measurement_source="CANN profiler timeline",
        expected_tool="CANN profiler",
        permission_need="profiler_permission",
        collection_overhead="high",
        expected_artifact="operator_timeline.jsonl",
        join_key=["trace_id", "phase", "layer_id", "stream_id"],
        time_base="cann_device_timeline",
        validation_method="run small model profile and verify timeline has ordered kernel events",
        acceptance_rule="partial if kernel events exist without request_id alignment",
        fallback="framework log operator timing if profiler unavailable",
    ))

    fields.extend(_profile_fields(
        "npu_hbm_profile",
        "hbm",
        [
            ("ai_core_util", "AI Core utilization", "counter", "percent"),
            ("aiv_util", "AIV utilization", "counter", "percent"),
            ("cube_util", "Cube utilization", "counter", "percent"),
            ("npu_busy_time_us", "NPU busy time", "metric", "us"),
            ("npu_idle_time_us", "NPU idle time", "metric", "us"),
            ("hbm_allocated_bytes", "allocated HBM bytes", "counter", "bytes"),
            ("hbm_reserved_bytes", "reserved HBM bytes", "counter", "bytes"),
            ("hbm_free_bytes", "free HBM bytes", "counter", "bytes"),
            ("hbm_peak_bytes", "peak HBM bytes", "counter", "bytes"),
            ("hbm_fragmentation_ratio", "HBM fragmentation ratio", "derived_metric", "ratio"),
            ("workspace_peak_bytes", "workspace peak bytes", "counter", "bytes"),
            ("kv_pool_bytes", "KV pool bytes", "counter", "bytes"),
            ("expert_cache_bytes", "expert cache bytes", "counter", "bytes"),
            ("hbm_read_gbps", "HBM read bandwidth", "counter", "GB/s"),
            ("hbm_write_gbps", "HBM write bandwidth", "counter", "GB/s"),
            ("hbm_stall_us", "HBM stall duration", "metric", "us"),
        ],
        required_for_p0=True,
        sampling_mode="periodic",
        measurement_source="npu-smi and CANN profiler counters",
        expected_tool="npu-smi, CANN profiler",
        permission_need="npu_visibility",
        collection_overhead="medium",
        expected_artifact="probe_results/npu_smi_probe.md",
        join_key=["profile_run_id", "npu_id", "timestamp_ns"],
        time_base="host_wall_clock_or_tool_timestamp",
        validation_method="compare repeated samples and verify non-negative counters",
        acceptance_rule="measurable if values are present for all visible NPUs",
        fallback="CANN profiler memory counters when npu-smi lacks field",
    ))

    fields.extend(_profile_fields(
        "cpu_dram_profile",
        "cpu_dram",
        [
            ("thread_name", "CPU thread name", "event", "text"),
            ("core_id", "CPU core identifier", "event", "count"),
            ("numa_node", "NUMA node identifier", "event", "count"),
            ("cpu_user_percent", "CPU user utilization", "counter", "percent"),
            ("cpu_sys_percent", "CPU system utilization", "counter", "percent"),
            ("cpu_iowait_percent", "CPU iowait utilization", "counter", "percent"),
            ("context_switches", "context switch count", "counter", "count"),
            ("runqueue_length", "runqueue length", "counter", "count"),
            ("scheduler_time_us", "scheduler time", "metric", "us"),
            ("tokenizer_time_us", "tokenizer time", "metric", "us"),
            ("sampler_time_us", "sampler time", "metric", "us"),
            ("cache_lookup_time_us", "cache lookup time", "metric", "us"),
            ("dram_read_gbps", "DRAM read bandwidth", "counter", "GB/s"),
            ("dram_write_gbps", "DRAM write bandwidth", "counter", "GB/s"),
            ("pinned_memory_bytes", "pinned memory bytes", "counter", "bytes"),
            ("page_faults", "page fault count", "counter", "count"),
            ("host_oom_event", "host OOM event", "event", "bool"),
        ],
        required_for_p0=True,
        sampling_mode="periodic",
        measurement_source="perf, pidstat, numastat, runtime logs",
        expected_tool="perf, pidstat, numastat",
        permission_need="host_perf_or_proc_access",
        collection_overhead="medium",
        expected_artifact="probe_results/perf_probe.md",
        join_key=["profile_run_id", "pid", "thread_id", "timestamp_ns"],
        time_base="host_monotonic_ns",
        validation_method="verify counters change during synthetic CPU workload",
        acceptance_rule="partial if process-level counters exist without request_id alignment",
        fallback="process-level ps and procfs samples",
    ))

    fields.extend(_profile_fields(
        "transfer_overlap_profile",
        "transfer",
        [
            ("direction", "copy direction", "event", "text"),
            ("transfer_bytes", "copy size", "counter", "bytes"),
            ("transfer_latency_us", "copy latency", "metric", "us"),
            ("effective_gbps", "effective transfer bandwidth", "metric", "GB/s"),
            ("setup_cost_us", "copy setup cost", "metric", "us"),
            ("copy_submit_ns", "copy submit timestamp", "event", "ns"),
            ("copy_complete_ns", "copy completion timestamp", "event", "ns"),
            ("copy_stream_id", "copy stream identifier", "event", "text"),
            ("compute_stream_id", "compute stream identifier", "event", "text"),
            ("compute_overlap_us", "compute time overlapping copy", "derived_metric", "us"),
            ("copy_exposed_us", "copy time exposed on critical path", "derived_metric", "us"),
            ("overlap_ratio", "copy and compute overlap ratio", "derived_metric", "ratio"),
            ("sync_barrier_event", "sync barrier event", "event", "text"),
            ("event_wait_us", "event wait duration", "metric", "us"),
        ],
        required_for_p0=True,
        sampling_mode="microbench",
        measurement_source="copy microbench and CANN timeline",
        expected_tool="custom copy microbench, CANN profiler",
        permission_need="npu_runtime_access",
        collection_overhead="medium",
        expected_artifact="copy_overlap_trace.csv",
        join_key=["trace_id", "stream_id", "object_id", "timestamp_ns"],
        time_base="host_monotonic_ns_and_cann_device_timeline",
        validation_method="compare no-overlap and intentional-overlap microbench runs",
        acceptance_rule="partial if host-side overlap estimate exists without device stream alignment",
        fallback="host-side submit and complete timestamps",
    ))

    fields.extend(_profile_fields(
        "ssd_io_profile",
        "ssd",
        [
            ("seq_read_gbps", "sequential read bandwidth", "metric", "GB/s"),
            ("seq_write_gbps", "sequential write bandwidth", "metric", "GB/s"),
            ("random_read_iops", "random read IOPS", "metric", "IOPS"),
            ("random_write_iops", "random write IOPS", "metric", "IOPS"),
            ("qd1_iops", "QD1 IOPS", "metric", "IOPS"),
            ("qd4_iops", "QD4 IOPS", "metric", "IOPS"),
            ("qd32_iops", "QD32 IOPS", "metric", "IOPS"),
            ("qd64_iops", "QD64 IOPS", "metric", "IOPS"),
            ("io_p50_us", "I/O p50 latency", "metric", "us"),
            ("io_p95_us", "I/O p95 latency", "metric", "us"),
            ("io_p99_us", "I/O p99 latency", "metric", "us"),
            ("io_p999_us", "I/O p999 latency", "metric", "us"),
            ("io_size_histogram", "I/O size histogram", "trace", "text"),
            ("direct_io_enabled", "direct I/O flag", "event", "bool"),
            ("page_cache_used", "page cache flag", "event", "bool"),
            ("mmap_used", "mmap flag", "event", "bool"),
            ("readahead_kb", "readahead size", "counter", "KB"),
            ("submit_path", "I/O submit path", "event", "text"),
            ("ssd_temperature_c", "SSD temperature", "counter", "C"),
            ("ssd_throttling_event", "SSD throttling event", "event", "bool"),
        ],
        required_for_p0=False,
        sampling_mode="microbench",
        measurement_source="fio, iostat, lsblk, smartctl when available",
        expected_tool="fio, iostat, lsblk",
        permission_need="block_device_read_access",
        collection_overhead="high",
        expected_artifact="probe_results/fio_probe.md",
        join_key=["profile_run_id", "device_id"],
        time_base="fio_timestamp",
        validation_method="verify fio reports non-empty latency and IOPS sections",
        acceptance_rule="measurable for capability profile if fio runs successfully on configured scratch path",
        fallback="lsblk and iostat inventory without workload",
    ))

    common_object_fields = [
        ("object_type", "state object type", "event", "text"),
        ("object_id", "state object identifier", "event", "text"),
        ("owner_request", "owning request identifier", "event", "text"),
        ("layer_id", "owning layer identifier", "event", "count"),
        ("object_bytes", "state object size", "counter", "bytes"),
        ("tier", "storage or memory tier", "event", "text"),
        ("lifecycle_event", "state object lifecycle event", "event", "text"),
        ("load_cost_us", "object load cost", "metric", "us"),
        ("evict_cost_us", "object evict cost", "metric", "us"),
        ("recompute_cost_us", "object recompute cost", "metric", "us"),
        ("hotness", "object hotness score", "derived_metric", "score"),
        ("next_use", "predicted next use", "derived_metric", "text"),
        ("consistency_scope", "object consistency scope", "event", "text"),
    ]
    fields.extend(_profile_fields(
        "state_object_profile",
        "state_object",
        common_object_fields,
        required_for_p0=True,
        sampling_mode="per_request",
        measurement_source="runtime object event hook",
        expected_tool="runtime hook or wrapper logger",
        permission_need="framework_hook",
        collection_overhead="medium",
        expected_artifact="state_object_trace.jsonl",
        join_key=["trace_id", "request_id", "object_id", "layer_id"],
        time_base="host_monotonic_ns",
        validation_method="verify create and delete lifecycle events for synthetic request objects",
        acceptance_rule="blocked until object_id and lifecycle_event are emitted",
        fallback="derive coarse object events from runtime logs",
    ))

    fields.extend(_profile_fields(
        "kv_prefix_profile",
        "state_object",
        [
            ("kv_object_id", "KV object identifier", "event", "text"),
            ("tokens_range", "token range covered by KV object", "event", "text"),
            ("block_size", "KV block size", "counter", "tokens"),
            ("block_table_entries", "KV block table entries", "counter", "count"),
            ("kv_fragmentation_ratio", "KV fragmentation ratio", "derived_metric", "ratio"),
            ("hit_tier", "tier where KV or prefix hit occurred", "event", "text"),
            ("miss_reason", "KV or prefix miss reason", "event", "text"),
            ("prefix_hash", "prefix hash", "event", "text"),
            ("matched_tokens", "matched prefix token count", "counter", "tokens"),
            ("position_shift", "prefix position shift", "metric", "tokens"),
            ("reuse_distance", "reuse distance", "metric", "requests"),
            ("restore_vs_recompute_decision", "restore versus recompute decision", "event", "text"),
        ],
        required_for_p0=True,
        sampling_mode="per_request",
        measurement_source="KV and prefix cache runtime hook",
        expected_tool="runtime hook or wrapper logger",
        permission_need="framework_hook",
        collection_overhead="medium",
        expected_artifact="state_object_trace.jsonl",
        join_key=["trace_id", "request_id", "object_id", "layer_id"],
        time_base="host_monotonic_ns",
        validation_method="run repeated-prefix workload and verify hit or miss events",
        acceptance_rule="partial if prefix hit is request-level only without per-layer KV block mapping",
        fallback="request-level prefix cache logs",
    ))

    fields.extend(_profile_fields(
        "moe_expert_profile",
        "state_object",
        [
            ("router_scores", "router scores or logits", "trace", "text"),
            ("top_k_expert_ids", "selected top-k expert identifiers", "trace", "text"),
            ("top_k_probs", "top-k expert probabilities", "trace", "text"),
            ("router_entropy", "router entropy", "derived_metric", "score"),
            ("expert_frequency", "expert frequency", "counter", "count"),
            ("expert_hotness", "expert hotness", "derived_metric", "score"),
            ("expert_reuse_distance", "expert reuse distance", "metric", "tokens"),
            ("expert_resident", "expert resident flag", "event", "bool"),
            ("expert_prefetched", "expert prefetched flag", "event", "bool"),
            ("expert_evicted", "expert evicted flag", "event", "bool"),
            ("expert_hit", "expert hit flag", "event", "bool"),
            ("expert_miss_tier", "tier where expert miss was served", "event", "text"),
            ("expert_load_latency_us", "expert load latency", "metric", "us"),
            ("prefetch_lead_time_us", "prefetch lead time", "metric", "us"),
            ("prefetch_accuracy", "prefetch accuracy", "derived_metric", "ratio"),
        ],
        required_for_p0=False,
        sampling_mode="per_layer",
        measurement_source="MoE router and expert cache hook",
        expected_tool="model hook or profiler operator mapping",
        permission_need="framework_hook",
        collection_overhead="high",
        expected_artifact="expert_trace.jsonl",
        join_key=["trace_id", "request_id", "layer_id", "object_id"],
        time_base="host_monotonic_ns",
        validation_method="run MoE workload and verify top-k expert ids exist for MoE layers",
        acceptance_rule="blocked until router top-k or expert cache events are emitted",
        fallback="operator-level MoE dispatch timing without expert identity",
    ))

    fields.extend(_profile_fields(
        "power_stability_profile",
        "power",
        [
            ("npu_power_w", "NPU power", "counter", "W"),
            ("cpu_power_w", "CPU package power", "counter", "W"),
            ("dram_power_w", "DRAM power", "counter", "W"),
            ("ssd_power_w", "SSD power", "counter", "W"),
            ("system_power_w", "system power", "counter", "W"),
            ("energy_per_token_j", "energy per token", "derived_metric", "J/token"),
            ("npu_temperature_c", "NPU temperature", "counter", "C"),
            ("cpu_temperature_c", "CPU temperature", "counter", "C"),
            ("ssd_temperature_c", "SSD temperature", "counter", "C"),
            ("npu_frequency_mhz", "NPU frequency", "counter", "MHz"),
            ("cpu_frequency_mhz", "CPU frequency", "counter", "MHz"),
            ("thermal_throttling_event", "thermal throttling event", "event", "bool"),
            ("oom_event", "OOM event", "event", "bool"),
            ("cann_error_event", "CANN error event", "event", "bool"),
            ("ssd_timeout_event", "SSD timeout event", "event", "bool"),
            ("long_run_p99_drift", "long run p99 drift", "derived_metric", "ratio"),
        ],
        required_for_p0=False,
        sampling_mode="periodic",
        measurement_source="npu-smi, system sensors, logs",
        expected_tool="npu-smi, sensors, journal logs",
        permission_need="host_sensor_access",
        collection_overhead="low",
        expected_artifact="probe_results/npu_smi_probe.md",
        join_key=["profile_run_id", "timestamp_ns"],
        time_base="host_wall_clock",
        validation_method="verify repeated samples remain within physical ranges",
        acceptance_rule="partial if NPU power and temperature are available without CPU or SSD power",
        fallback="temperature-only stability tracking",
    ))

    fields.extend(_profile_fields(
        "microbench_profile",
        "microbench",
        [
            ("npu_op_by_shape", "NPU operator latency by shape", "trace", "text"),
            ("cpu_kernel_by_shape", "CPU kernel latency by shape", "trace", "text"),
            ("ddr_bandwidth_gbps", "DDR bandwidth", "metric", "GB/s"),
            ("ssd_iops", "SSD IOPS", "metric", "IOPS"),
            ("h2d_latency_us", "H2D latency", "metric", "us"),
            ("d2h_latency_us", "D2H latency", "metric", "us"),
            ("h2d_bandwidth_gbps", "H2D bandwidth", "metric", "GB/s"),
            ("d2h_bandwidth_gbps", "D2H bandwidth", "metric", "GB/s"),
            ("pageable_copy_latency_us", "pageable copy latency", "metric", "us"),
            ("pinned_copy_latency_us", "pinned copy latency", "metric", "us"),
            ("sync_copy_latency_us", "sync copy latency", "metric", "us"),
            ("async_copy_latency_us", "async copy latency", "metric", "us"),
            ("copy_overlap_ratio", "copy overlap ratio", "derived_metric", "ratio"),
        ],
        required_for_p0=True,
        sampling_mode="microbench",
        measurement_source="safe microbench commands and existing tools",
        expected_tool="fio, perf, CANN sample or custom copy microbench",
        permission_need="tool_specific_access",
        collection_overhead="high",
        expected_artifact="probe_results/fio_probe.md",
        join_key=["profile_run_id", "benchmark_id"],
        time_base="host_monotonic_ns",
        validation_method="verify command exits zero and reports numeric metric",
        acceptance_rule="partial if inventory and tool availability are verified before workload execution",
        fallback="record tool availability only",
    ))

    return fields
