import type {
  AkStage,
  GlmComponent,
  GlmFlowStep,
  GlmModelFact,
  GlmPathComparison,
  HardwareEdge,
  HardwareLayer,
  HardwareNode,
  LayerId,
  SimulatorModule,
  StateObject,
  WorkItem,
} from "./types";

export const hardwareLayers: HardwareLayer[] = [
  {
    id: "L0",
    name: "workload 与阶段",
    hardware: "arrival、prompt/output 长度、session reuse、agent idle、prefill/decode",
    bottleneck: "平均负载掩盖 burst、prefix reuse 和长尾。",
    representativeMoves: "ServeGen 做真实 workload characterization；BurstGPT 提供 burst trace；LLMServingSim2.0 做 trace-driven replay。",
    simFields: "arrival process、prompt/output 分布、reuse distance、并发、SLO",
  },
  {
    id: "L1",
    name: "加速器计算核心",
    hardware: "GPU SM/Tensor Core、Ascend AI Core/Cube、mobile NPU INT8 单元",
    bottleneck: "prefill 算力密集，decode 小 batch 利用率低。",
    representativeMoves: "llm.npu 强化 NPU prefill；NEO 保留 GPU 线性层并把部分 decode attention 放 CPU；FlexInfer 按 phase 选 CPU/GPU 策略。",
    simFields: "operator latency by shape、batch evolution、utilization、kernel launch overhead",
  },
  {
    id: "L2",
    name: "加速器片上/本地内存",
    hardware: "HBM/GDDR/NPU memory、L2/SRAM、workspace",
    bottleneck: "KV、weights、activation、workspace 抢容量。",
    representativeMoves: "PagedAttention/LMCache/Mooncake/UCM 把 KV 对象化；FineMoE/DALI/FluxMoE 把 expert 对象化。",
    simFields: "HBM occupancy、block size、KV bytes/token、expert size、eviction count",
  },
  {
    id: "L3",
    name: "加速器状态布局",
    hardware: "KV block、prefix tree、expert cache、paged layout",
    bottleneck: "逻辑连续对象被物理分页打散，恢复时变成小 I/O。",
    representativeMoves: "Tutti 把 KV 变成 GPU-native object；CacheSlide 处理 prefix 位置偏移；SolidAttention 用粗粒度 KV blocks 和稀疏访问。",
    simFields: "object ID、layer/block layout、fragmentation、I/O size distribution",
  },
  {
    id: "L4",
    name: "DMA 与设备流",
    hardware: "PCIe DMA、D2H/H2D、copy engine、NPU stream、P2P",
    bottleneck: "传输和同步挡住主链路。",
    representativeMoves: "NEO 避免反复 KV swap，改为 CPU 侧 attention；vLLM-Ascend 用独立 NPU stream 做 D2H/H2D；Tutti 去掉 CPU critical I/O path。",
    simFields: "transfer bytes、setup latency、overlap ratio、sync barrier、stall attribution",
  },
  {
    id: "L5",
    name: "CPU 计算",
    hardware: "x86 AMX/AVX-512、ARM SVE/SME、Kunpeng cores",
    bottleneck: "CPU FLOPs 弱，但内存容量大；小矩阵/同步开销高。",
    representativeMoves: "KTransformers 用 AMX expert kernel 和 Expert Deferral；FlexInfer 引入 CPU computation policy；NEO 只 offload 部分 decode attention。",
    simFields: "CPU kernel latency、SIMD ISA、cores、cache miss、CPU utilization",
  },
  {
    id: "L6",
    name: "CPU 内存与 NUMA",
    hardware: "DDR、NUMA socket、pinned memory、CPU KV pool、host cache",
    bottleneck: "DDR 带宽、NUMA 跨 socket、host OOM、pinned buffer 争用。",
    representativeMoves: "NEO 利用 host CPU memory 放 KV；KTransformers 做 NUMA-aware tensor placement；Bidaw 用 host memory + SSD 两级 KV。",
    simFields: "DDR bandwidth、NUMA locality、pool hit/miss、pinned bytes、host OOM",
  },
  {
    id: "L7",
    name: "机内互联",
    hardware: "PCIe 4/5、NVLink/NVSwitch、UB/HCCS/HCCL、CXL.mem",
    bottleneck: "带宽/延迟决定 offload 边界；小粒度频繁往返最危险。",
    representativeMoves: "FlexInfer 证明 PCIe data load 可支配 offload 时间；Mooncake/TensorRT-LLM/Dynamo 显式建模 KV transfer；ITME 把 CXL 作为容量层。",
    simFields: "per-link bandwidth/latency、P2P capability、queue depth、contention",
  },
  {
    id: "L8",
    name: "本地存储",
    hardware: "NVMe SSD、SSD queue、file system、GDS、GPU io_uring、Mooncake SSD offload",
    bottleneck: "账面带宽高但 tiny random I/O、CPU control path 和 DRAM-HBM copy 会反噬。",
    representativeMoves: "Tutti 用 GPU-centric object I/O；Bidaw 做 two-tier storage-aware scheduling；SolidAttention 做 sparse KV + SSD orchestration；vLLM-Ascend KV Pool 支持 Mooncake SSD offload。",
    simFields: "SSD seq/random BW、IOPS、I/O size、submit/completion path、buffer alignment",
  },
  {
    id: "L9",
    name: "远端数据面",
    hardware: "RDMA、RoCE/IB、NIXL、Mooncake Transfer Engine、remote H2D",
    bottleneck: "P/D 分离后 KV transfer 可能比计算更贵。",
    representativeMoves: "Mooncake 做 KVCache-centric disaggregation；vLLM NixlConnector/Dynamo 用 NIXL 和 KV-aware routing；vLLM-Ascend KV Pool 提供 MooncakeConnectorV1。",
    simFields: "KV transfer bytes、network RTT/BW、routing policy、remote hit/miss、backpressure",
  },
  {
    id: "L10",
    name: "运行时控制面",
    hardware: "scheduler、queue、cache manager、metadata、connector API",
    bottleneck: "cache 命中和硬件利用由调度决定，不是硬件自动解决。",
    representativeMoves: "NEO load-aware scheduling；Mooncake Conductor；Bidaw ready/preparing queue；UCM/LMCache/vLLM connectors。",
    simFields: "queueing delay、policy decision、object lifecycle、TTL、QoS",
  },
  {
    id: "L11",
    name: "可观测与能耗",
    hardware: "profiler、counters、power、temperature、trace schema",
    bottleneck: "无法判断瓶颈是在 compute、copy、I/O、queue 还是 cache miss。",
    representativeMoves: "ProfInfer 做 timeline/counter；LLMServingSim2.0 做 operator-level profiler + memory/power simulator。",
    simFields: "TTFT、TPOT、P95/P99、energy/token、power curve、simulation error",
  },
];

export const hardwareNodes: HardwareNode[] = [
  { id: "telemetry", label: "Telemetry / 仿真器", group: "observe", role: "timeline、counters、power、stall attribution、simulation error。", linkedLayers: ["L0", "L11"], x: 20, y: 20 },
  { id: "ledger", label: "统一 State Object Ledger", group: "runtime", role: "把 KV、expert、prefix、weight、activation 统一成可调度对象。", linkedLayers: ["L2", "L3", "L10"], x: 520, y: 20 },
  { id: "hbm", label: "HBM / NPU memory", group: "memory", role: "weights、KV hot blocks、activation、workspace 争用的核心容量层。", linkedLayers: ["L2", "L3"], x: 770, y: 20 },
  { id: "request", label: "请求 / 会话", group: "request", role: "prompt、output、reuse、arrival 与 SLO 的入口。", linkedLayers: ["L0"], x: 20, y: 280 },
  { id: "runtime", label: "Runtime 控制面", group: "runtime", role: "scheduler、tokenizer、sampler、cache manager、connector API。", linkedLayers: ["L0", "L10"], x: 270, y: 280 },
  { id: "accelerator", label: "GPU / Ascend NPU", group: "accelerator", role: "prefill、decode、attention、FFN、MoE gate 的热路径主算。", linkedLayers: ["L1", "L2"], x: 520, y: 280 },
  { id: "state-layout", label: "KV / Expert / Prefix 布局", group: "memory", role: "block、page、radix tree、expert cache 等状态对象布局。", linkedLayers: ["L2", "L3"], x: 770, y: 280 },
  { id: "cpu", label: "Kunpeng / CPU cores", group: "host", role: "控制面、metadata、decode attention 子路径、expert fallback、I/O 聚合。", linkedLayers: ["L5", "L10"], x: 270, y: 540 },
  { id: "dma", label: "PCIe / DMA / Stream", group: "fabric", role: "D2H、H2D、P2P、copy engine、NPU stream 与同步屏障。", linkedLayers: ["L4", "L7"], x: 520, y: 540 },
  { id: "nic", label: "NIC / RDMA / NIXL", group: "fabric", role: "P/D transfer、KV exchange、remote H2D、Mooncake transfer。", linkedLayers: ["L9"], x: 1020, y: 540 },
  { id: "ddr", label: "CPU DDR / NUMA", group: "host", role: "KV warm tier、expert warm tier、pinned memory、host cache。", linkedLayers: ["L6"], x: 520, y: 780 },
  { id: "ssd", label: "NVMe / SSD / FS", group: "storage", role: "KV cold tier、expert cold tier、object store、Mooncake SSD offload。", linkedLayers: ["L8"], x: 770, y: 780 },
  { id: "remote", label: "Remote KV / CXL / Fabric Mem", group: "storage", role: "远端内存、CXL 容量层、persistent KV 与 disaggregated KV pool。", linkedLayers: ["L7", "L9"], x: 1020, y: 780 },
];

export const hardwareEdges: HardwareEdge[] = [
  { from: "request", to: "runtime", label: "arrival / SLO / reuse", pathType: "control", relatedWorks: ["servegen", "llmservingsim2", "burstgpt", "bidaw", "mooncake", "cacheslide"] },
  { from: "runtime", to: "accelerator", label: "prefill / decode dispatch", pathType: "hot", relatedWorks: ["neo", "flexinfer", "llm-npu", "mooncake", "dynamo", "bidaw", "solidattention", "ktransformers", "finemoe", "dali", "fluxmoe"] },
  { from: "accelerator", to: "hbm", label: "weights / hot KV / workspace", pathType: "hot", relatedWorks: ["neo", "mooncake", "lmcache-ucm", "tutti", "solidattention", "ktransformers", "finemoe", "dali", "fluxmoe", "vllm-ascend-cpu-offload", "vllm-ascend-ucm-kv-pool"] },
  { from: "accelerator", to: "state-layout", label: "paged KV / prefix / expert cache", pathType: "hot", relatedWorks: ["tutti", "cacheslide", "solidattention", "lmcache-ucm", "ktransformers", "finemoe", "dali", "fluxmoe"] },
  { from: "accelerator", to: "dma", label: "D2H / H2D / copy stream", pathType: "warm", relatedWorks: ["neo", "flexinfer", "finemoe", "dali", "fluxmoe", "lmcache-ucm", "vllm-ascend-cpu-offload"] },
  { from: "dma", to: "cpu", label: "small tensors / control sync", pathType: "warm", relatedWorks: ["neo", "flexinfer", "llm-npu", "ktransformers", "dali"] },
  { from: "cpu", to: "ddr", label: "host KV / expert warm tier", pathType: "warm", relatedWorks: ["neo", "mooncake", "lmcache-ucm", "ktransformers", "finemoe", "dali", "fluxmoe", "bidaw", "vllm-ascend-cpu-offload"] },
  { from: "ddr", to: "ssd", label: "cold KV / spill / storage tier", pathType: "cold", relatedWorks: ["lmcache-ucm", "bidaw", "solidattention", "cacheslide", "vllm-ascend-ucm-kv-pool"] },
  { from: "dma", to: "ssd", label: "P2P / object I/O", pathType: "cold", relatedWorks: ["tutti"] },
  { from: "dma", to: "nic", label: "remote H2D / KV transfer", pathType: "remote", relatedWorks: ["mooncake", "dynamo", "vllm-ascend-ucm-kv-pool"] },
  { from: "nic", to: "remote", label: "RDMA / NIXL / Mooncake", pathType: "remote", relatedWorks: ["mooncake", "dynamo", "vllm-ascend-ucm-kv-pool"] },
  { from: "runtime", to: "ledger", label: "object lifecycle / TTL / policy", pathType: "control", relatedWorks: ["lmcache-ucm", "mooncake", "cacheslide", "llmservingsim2", "finemoe", "dali", "fluxmoe", "tutti"] },
  { from: "ledger", to: "state-layout", label: "state object index", pathType: "control", relatedWorks: ["lmcache-ucm", "tutti", "cacheslide", "ktransformers", "finemoe", "dali", "fluxmoe"] },
  { from: "telemetry", to: "runtime", label: "queue / policy / counters", pathType: "observe", relatedWorks: ["profinfer", "llmservingsim2", "servegen"] },
  { from: "telemetry", to: "accelerator", label: "operator / memory / power", pathType: "observe", relatedWorks: ["profinfer", "llmservingsim2", "llm-npu"] },
];

export const works: WorkItem[] = [
  {
    id: "neo",
    name: "NEO",
    category: "GPU/NPU + CPU 协同",
    hardwarePath: ["GPU/HBM", "PCIe/DMA", "CPU cores", "CPU DDR", "load-aware scheduler", "NUMA boundary"],
    topology: {
      summary: "部分 decode attention 和对应 KV 留在 CPU/CPU memory，GPU 继续承担 prefill、线性层和 GPU-side attention。",
      primaryPath: ["GPU/HBM hot compute", "PCIe/DMA layer-wise transfer", "CPU cores decode attention", "CPU DDR KV cache", "load-aware scheduler"],
      hardwareClaims: ["GPU/HBM 保存模型、activation 与 GPU-request KV", "CPU memory 保存 CPU-request KV", "CPU cores 执行 PACPU decode attention", "PCIe 传必要张量并做 layer-wise KV transmission"],
      nonClaims: "不是普通 KV swap，也不是把整条推理主链路搬到 CPU；NUMA 不是原文核心机制。",
      criticalAssumption: "CPU attention 能被 GPU prefill/linear/attention 覆盖，且 CPU memory bandwidth 没有成为新瓶颈。",
      frontendHighlight: "高亮 GPU/HBM -> PCIe/DMA -> CPU cores -> CPU DDR -> scheduler；NUMA 只作为 CPU memory 风险。",
      frontendWarning: "不要写成 KV offload 到 CPU 后每步搬回 GPU，也不要泛化为 CPU 普遍加速推理。",
      highlightNodeIds: ["runtime", "accelerator", "hbm", "dma", "cpu", "ddr"],
    },
    layers: ["L1", "L2", "L4", "L5", "L6", "L10"],
    stateObjects: ["KV cache", "attention state"],
    solves: "GPU memory 限制 batch/concurrency，单纯 KV swap 会被 PCIe 带宽卡住。",
    approach: "把部分 decode attention compute 和 KV 状态放到本地 CPU；GPU 继续跑线性/主算；用 asymmetric GPU-CPU pipeline 和 load-aware scheduling 平衡 CPU/GPU。",
    boundary: "CPU 内存带宽和 kernel 能力是上限；只适合可重叠、内存带宽型 decode attention 子路径。",
    akRelevance: "对应 Kunpeng warm tier + 可重叠 CPU 计算验证，但不能笼统称为 CPU 加速推理。",
    evidence: ["references/papers/NEO__arxiv-2411.01142.pdf"],
  },
  {
    id: "flexinfer",
    name: "FlexInfer",
    category: "GPU/NPU + CPU 协同",
    hardwarePath: ["single GPU", "CPU", "PCIe", "CPU matrix unit"],
    topology: {
      summary: "按 prefill/decode 阶段在 CPU-only、GPU tensor offload、CPU-GPU static partitioning/SplitGen 之间选择策略。",
      primaryPath: ["Execution Planner", "CPU memory / CPU compute", "PCIe interconnect", "GPU memory / GPU compute"],
      hardwareClaims: ["CPU memory 容纳权重、KV、activation", "CPU matrix unit 影响 CPU-only 策略", "GPU memory 支撑 SplitGen 常驻层", "PCIe bandwidth 直接进入策略代价模型"],
      nonClaims: "不是固定 CPU/GPU 切分，也不是某一条 offload 路径在所有场景最优。",
      criticalAssumption: "必须有目标 CPU/GPU throughput、memory bandwidth、PCIe bandwidth 和 shape profile。",
      frontendHighlight: "展示策略选择器，连接 CPU memory/compute、PCIe、GPU memory/compute。",
      frontendWarning: "Kunpeng SVE/SME 不能从 Intel AMX/TMUL 结果直接外推。",
      highlightNodeIds: ["runtime", "accelerator", "hbm", "dma", "cpu", "ddr"],
    },
    layers: ["L1", "L4", "L5", "L7", "L10"],
    stateObjects: ["weights", "KV cache"],
    solves: "offloading 模型权重/KV 到 CPU memory 后，PCIe data load 暴露时间过高。",
    approach: "在 CPU computation、GPU offload execution、CPU-GPU static partitioning 间按 phase、batch、seq length、硬件配置选择策略。",
    boundary: "大 batch/长输入时 CPU compute 可能变瓶颈；策略需要硬件实测参数。",
    akRelevance: "适合抽象成 A+K 策略选择器的 baseline，但 Kunpeng 向量能力要单独测。",
    evidence: ["references/papers/FlexInfer.pdf"],
  },
  {
    id: "llm-npu",
    name: "llm.npu",
    category: "端侧 NPU 异构调度",
    hardwarePath: ["mobile NPU", "CPU/GPU fallback", "SoC memory", "out-of-order subgraph"],
    topology: {
      summary: "端侧 NPU 主跑适合 INT8 的 prefill 子图，CPU/GPU 处理 outlier、float 和动态 fallback。",
      primaryPath: ["mobile NPU prefill", "CPU/GPU outlier shadow path", "shared SoC memory", "OOO graph scheduler"],
      hardwareClaims: ["移动 NPU 执行固定 shape INT8 MatMul", "CPU/GPU 执行 outlier 和 FP fallback", "SoC shared memory 不等同服务器 PCIe 显存", "runtime/compiler 负责静态图与 OOO subgraph"],
      nonClaims: "不是服务器 Ascend 结论，也不是 decode KV 分层或 SSD/RDMA 路线。",
      criticalAssumption: "NPU 主路径能覆盖 outlier/fallback 与图准备开销。",
      frontendHighlight: "只高亮 NPU/accelerator、CPU fallback 和 runtime scheduler。",
      frontendWarning: "方法论可迁移，服务器 Ascend+Kunpeng 需要重新 profile。",
      highlightNodeIds: ["runtime", "accelerator", "cpu", "telemetry"],
    },
    layers: ["L1", "L3", "L5", "L10", "L11"],
    stateObjects: ["activation", "outlier operator", "subgraph"],
    solves: "端侧 prefill 慢，NPU 静态 shape、outlier、FP operator 支持弱。",
    approach: "prompt chunk-sharing graph、shadow outlier CPU/GPU parallel execution、out-of-order subgraph scheduling。",
    boundary: "主要覆盖移动端 prefill；与服务器 Ascend/Kunpeng 不能直接等价。",
    akRelevance: "给 Ascend+Kunpeng 的异构图重写和 fallback 策略提供参考。",
    evidence: ["references/papers/llm.npu__arxiv-2407.05858.pdf"],
  },
  {
    id: "ktransformers",
    name: "KTransformers",
    category: "MoE expert 分层",
    hardwarePath: ["GPU VRAM", "CPU DDR", "AMX/AVX", "NUMA", "CUDA Graph"],
    topology: {
      summary: "shared/hot experts 留在 GPU，routed experts 常驻 CPU，并用 AMX/AVX、NUMA-aware placement 和 Expert Deferral 做 CPU-GPU overlap。",
      primaryPath: ["GPU shared experts", "CPU DRAM routed experts", "CPU AMX/AVX compute", "NUMA placement", "CPU-GPU async scheduler"],
      hardwareClaims: ["GPU VRAM 放 attention/shared experts", "CPU DRAM 常驻 routed experts", "CPU AMX/AVX-512 跑 expert kernel", "NUMA-aware tensor placement 是核心机制"],
      nonClaims: "不适用于非 MoE dense model；不是简单把 expert 从 SSD 搬回 GPU。",
      criticalAssumption: "CPU SIMD kernel、DDR/NUMA locality 和 CPU-GPU 同步开销必须足够好。",
      frontendHighlight: "高亮 GPU VRAM、CPU DDR/NUMA、CPU cores 和 runtime scheduler。",
      frontendWarning: "AMX/CUDA Graph 结论不能直接继承到 Kunpeng+Ascend。",
      highlightNodeIds: ["runtime", "accelerator", "hbm", "cpu", "ddr", "state-layout"],
    },
    layers: ["L2", "L5", "L6", "L10"],
    stateObjects: ["MoE expert", "weights"],
    solves: "本地大 MoE 放不进 GPU，expert weight 频繁 PCIe 搬运会慢。",
    approach: "shared/hot experts 留 GPU，routed experts 放 CPU；AMX-specialized expert kernel；NUMA-aware placement；Expert Deferral 重叠 CPU/GPU。",
    boundary: "强依赖 CPU ISA 和内存带宽；Kunpeng SVE 需要独立 microbenchmark。",
    akRelevance: "可作为 Kunpeng SVE expert kernel 的对照目标，但不能直接继承 AMX 结论。",
    evidence: ["references/papers/KTransformers.pdf"],
  },
  {
    id: "finemoe",
    name: "FineMoE",
    category: "MoE expert 分层",
    hardwarePath: ["GPU memory", "CPU memory", "expert cache", "semantic hints"],
    topology: {
      summary: "用 semantic hints 和 iteration-level expert map 指导 GPU expert cache 的 prefetch、cache 与 offload。",
      primaryPath: ["prompt semantic / trajectory", "Expert Map", "CPU DRAM experts", "PCIe prefetch", "GPU expert cache"],
      hardwareClaims: ["GPU memory 是 expert cache hot tier", "CPU memory 是 offloaded expert warm tier", "PCIe 承载 expert prefetch/on-demand load", "Expert Map Store/Searcher 是控制面"],
      nonClaims: "不是 SSD/remote expert pool，也不解决所有 expert selection 预测问题。",
      criticalAssumption: "prompt semantic 与 expert trajectory 有可复用的预测性。",
      frontendHighlight: "高亮 runtime/state-layout、CPU DRAM、PCIe/DMA 和 GPU/HBM expert cache。",
      frontendWarning: "需要暴露 MoE gate/expert IDs 和可控 prefetch API。",
      highlightNodeIds: ["runtime", "ledger", "state-layout", "accelerator", "hbm", "dma", "ddr"],
    },
    layers: ["L2", "L3", "L6", "L10"],
    stateObjects: ["MoE expert"],
    solves: "coarse expert offload 导致 miss 多、延迟高或显存占用高。",
    approach: "expert map 记录 iteration-level expert distribution，结合 semantic hints 做 prefetch/cache/offload。",
    boundary: "router 可预测性不足时收益下降；需要 expert trace 和 hit/miss 实测。",
    akRelevance: "适合并入统一 state object hotness/next_use 字段。",
    evidence: ["references/papers/fMoE-FineMoE__arxiv-2502.05370.pdf"],
  },
  {
    id: "dali",
    name: "DALI",
    category: "MoE expert 分层",
    hardwarePath: ["CPU DRAM all experts", "GPU expert cache", "CPU cores", "PCIe prefetch", "workload-aware assignment"],
    topology: {
      summary: "按当前 MoE layer 的 expert workload 动态分配 CPU/GPU，并用 residual prefetch 与 workload-aware replacement 提高 GPU expert cache 命中。",
      primaryPath: ["CPU DRAM all experts", "Greedy Assignment", "CPU low-workload experts", "GPU high-workload expert cache", "PCIe prefetch"],
      hardwareClaims: ["CPU DRAM 存所有 expert weights", "GPU memory 缓存高 workload experts", "CPU cores 执行低 workload experts", "PCIe 负责 GPU miss/prefetch"],
      nonClaims: "不是数据中心 expert parallelism，也不同于 KTransformers 的 AMX/NUMA/Expert Deferral 主线。",
      criticalAssumption: "expert workload temporal locality 和 residual-based prefetch 足够有效。",
      frontendHighlight: "高亮 CPU DDR、CPU cores、PCIe/DMA、GPU/HBM、runtime assignment。",
      frontendWarning: "若 Kunpeng expert kernel 或 PCIe/NPU load 不达标，assignment 会被硬件瓶颈反噬。",
      highlightNodeIds: ["runtime", "cpu", "ddr", "dma", "accelerator", "hbm", "state-layout"],
    },
    layers: ["L2", "L3", "L5", "L6", "L10"],
    stateObjects: ["MoE expert"],
    solves: "静态 expert assignment 造成 CPU/GPU load imbalance，高 workload expert miss 时 PCIe transfer 成为主要开销。",
    approach: "Greedy Assignment、residual-based prefetch、workload-aware cache replacement。",
    boundary: "expert locality 弱、CPU expert kernel 弱或 PCIe 太慢时收益下降。",
    akRelevance: "可作为 A+K expert 动态分配与预取策略的对照。",
    evidence: ["references/papers/DALI__arxiv-2602.03495.pdf"],
  },
  {
    id: "fluxmoe",
    name: "FluxMoE",
    category: "MoE expert 分层",
    hardwarePath: ["KV priority in HBM", "PagedTensor", "compressed GPU backend", "host DRAM expert backend", "PCIe materialization"],
    topology: {
      summary: "把 expert weights 从长期 GPU 常驻状态改成按 layer materialize 的 streamed resource，把 GPU memory 优先留给 KV 和 activation。",
      primaryPath: ["KV cache priority in HBM", "PagedTensor handles", "compressed GPU expert backend", "host DRAM expert backend", "PCIe materialization"],
      hardwareClaims: ["GPU virtual handles 稳定暴露给 kernel", "GPU physical buffers 只保留 sliding working set", "host DRAM backend 保存 offloaded experts", "budget-aware planner 按 KV pressure 调整 expert residency"],
      nonClaims: "不预测下一步 expert selection；重点是 residency/paging，不是 FineMoE/DALI 式 expert 选择预取。",
      criticalAssumption: "runtime 支持稳定虚拟地址/同步屏障，且 materialization 不挡住 forward pass。",
      frontendHighlight: "高亮 HBM KV 优先、state-layout/PagedTensor、CPU DRAM expert backend、PCIe/DMA。",
      frontendWarning: "前端证据必须指向 arXiv 2604.02715v2；旧 2601.07343 是无关论文。",
      highlightNodeIds: ["runtime", "ledger", "state-layout", "accelerator", "hbm", "dma", "ddr"],
    },
    layers: ["L2", "L3", "L4", "L6", "L10"],
    stateObjects: ["MoE expert", "KV cache", "activation / workspace"],
    solves: "MoE expert weights 长期常驻 GPU memory，和 KV cache/activation 争 HBM，限制 memory-constrained decode。",
    approach: "Expert paging、PagedTensor、compressed GPU backend、host DRAM backend、budget-aware residency planner。",
    boundary: "依赖 runtime 虚拟化和 materialization overlap；Ascend/CANN 需要重新验证。",
    akRelevance: "可作为 A+K expert residency 与 KV 优先级调度的设计参照。",
    evidence: ["references/papers/FluxMoE__arxiv-2604.02715v2.pdf"],
  },
  {
    id: "mooncake",
    name: "Mooncake",
    category: "KV 分层与远端数据面",
    hardwarePath: ["GPU/VRAM", "CPU/DRAM", "SSD", "RDMA", "global scheduler"],
    topology: {
      summary: "P/D 分离后，把 CPU、DRAM、SSD、RDMA 组织成 disaggregated KVCache pool，由 Conductor 按 KV 分布与负载调度。",
      primaryPath: ["request / Conductor", "prefill GPU", "CPU DRAM KV pool", "RDMA Messenger", "decode CPU DRAM", "decode GPU"],
      hardwareClaims: ["prefill/decode GPU 分离", "CPU DRAM KV pool 保存 paged KV blocks", "RDMA/Messenger 负责跨实例 KV transfer", "Conductor 是全局 KV-aware scheduler"],
      nonClaims: "SSD 是可选容量资源，不是每个 Mooncake 请求的必经 fast path。",
      criticalAssumption: "长上下文、高复用、transfer 可重叠且网络不过载。",
      frontendHighlight: "拆成 Conductor 控制面、Messenger/RDMA 远端数据面、CPU DRAM 温层和 GPU hot path。",
      frontendWarning: "单机 A+K 应提取 KV object + host pool + connector，不要照搬完整集群架构。",
      highlightNodeIds: ["request", "runtime", "accelerator", "hbm", "cpu", "ddr", "nic", "remote", "ledger"],
    },
    layers: ["L2", "L6", "L8", "L9", "L10"],
    stateObjects: ["KV cache", "prefix"],
    solves: "长上下文和多轮对话下 KV 复用/迁移/调度成为中心问题。",
    approach: "KVCache-centric disaggregation；prefill/decode 分离；CPU/DRAM/SSD 组成 disaggregated KV pool；Conductor 做 KV-aware scheduling。",
    boundary: "P/D 拆分只在长上下文、高复用、可重叠 transfer 下赚钱。",
    akRelevance: "对应 vLLM-Ascend KV Pool / MooncakeConnectorV1 的核心路线。",
    evidence: ["references/papers/Mooncake__arxiv-2407.00079.pdf"],
  },
  {
    id: "lmcache-ucm",
    name: "LMCache / UCM",
    category: "外部 KV 与状态对象 API",
    hardwarePath: ["HBM", "DRAM", "storage backend", "external KV API"],
    topology: {
      summary: "在 inference engine 与 GPU/CPU/SSD/remote backend 之间提供 KV cache layer/API 和多级数据搬运。",
      primaryPath: ["engine connector", "GPU buffer / HBM", "CPU DRAM", "SSD or remote backend", "cache controller / token pool"],
      hardwareClaims: ["KV connector 解耦 engine metadata", "GPU streaming buffer 合并 paged KV", "CPU DRAM/local disk/remote backend 构成多级存储", "cache controller 支持 locate/move/pin/evict"],
      nonClaims: "不是 Tutti 式 GPU-native SSD direct path，也不是固定硬件拓扑。",
      criticalAssumption: "chunk size、prefix hit rate、backend latency 和 router 策略足够匹配 workload。",
      frontendHighlight: "高亮 runtime connector、HBM、CPU DRAM、SSD/remote backend 和 state object ledger。",
      frontendWarning: "SSD tiny I/O、CPU overhead 和 GDS control path 仍可能需要 Tutti 类底层优化。",
      highlightNodeIds: ["runtime", "ledger", "accelerator", "hbm", "state-layout", "ddr", "ssd", "nic", "remote"],
    },
    layers: ["L2", "L3", "L6", "L8", "L10"],
    stateObjects: ["KV cache", "prefix"],
    solves: "prefix/KV 复用局限在单 engine 或单设备内存。",
    approach: "KV object API、多级 storage backend、pin/lookup/move/compress/evict；UCM 用 HBM -> DRAM -> SSD/NFS/3FS 分层。",
    boundary: "object consistency、TTL、跨 DP 命中和 storage backend 延迟要单独建模。",
    akRelevance: "是 A+K 统一 state object runtime 的直接接口基础。",
    evidence: ["references/papers/LMCache__arxiv-2510.09665.pdf", "references/web/vLLM-Ascend-UCM-deployment-live.html"],
  },
  {
    id: "bidaw",
    name: "Bidaw",
    category: "SSD / host memory 两级 KV",
    hardwarePath: ["GPU", "host memory", "SSD", "two-tier storage", "ready/preparing queue"],
    topology: {
      summary: "把交互式多轮 KV 放在 host memory + SSD 两级存储，并让 compute scheduler 感知 KV 位置与大小。",
      primaryPath: ["request scheduler", "ready / preparing queue", "CPU DDR host memory", "SSD capacity layer", "GPU inference"],
      hardwareClaims: ["host memory 是 performance layer", "SSD 是 capacity layer", "ready/preparing queue 按 KV 所在层调度", "eviction 用上一轮回答长度估计复用距离"],
      nonClaims: "不是 GPU direct SSD，也不是 P/D 远端 KV 系统。",
      criticalAssumption: "workload 是 interactive multi-round，KV reuse 和 previous-answer-based eviction 信号有效。",
      frontendHighlight: "高亮 request/runtime queue、CPU DDR、SSD、GPU 消费端。",
      frontendWarning: "SSD miss 多或 host memory 太小时 preparing queue 会堆积，P99 仍可能恶化。",
      highlightNodeIds: ["request", "runtime", "cpu", "ddr", "ssd", "accelerator"],
    },
    layers: ["L6", "L8", "L10"],
    stateObjects: ["KV cache"],
    solves: "交互式多轮 KV 从两级存储加载时，慢 I/O 请求阻塞快请求。",
    approach: "compute-storage 双向感知；ready/preparing queue；按 KV 所在层和大小调度；用响应长度预测 eviction。",
    boundary: "依赖对用户下一次访问的预测；适合多轮会话 KV，而非所有 workload。",
    akRelevance: "可用于 A+K SSD cold tier 的调度反例和排队模型。",
    evidence: ["references/papers/Bidaw-FAST26.pdf"],
  },
  {
    id: "solidattention",
    name: "SolidAttention",
    category: "SSD + sparse KV",
    hardwarePath: ["GPU/HBM", "SSD", "sparse KV blocks", "I/O orchestration"],
    topology: {
      summary: "把完整 KV 放 SSD，只把 dynamic sparse attention 选中的 KV blocks 装入 GPU，并让 KV block 粒度、预取和调度匹配 SSD I/O。",
      primaryPath: ["SSD KV blocks", "DRAM buffer", "GPU VRAM", "sparse attention compute", "prefetch / scheduler"],
      hardwareClaims: ["SSD 保存完整 KV", "DRAM buffer 是 host-mediated transfer 辅助层", "GPU VRAM 只保留选中的 KV blocks", "KV consolidator 与 SSD-aware scheduler 协调 I/O 粒度"],
      nonClaims: "不是 Tutti 式 GPU-native SSD direct path，也不是 dense attention 通用扩容。",
      criticalAssumption: "attention sparsity 有效，block 粒度能兼顾 retrieval quality 和 SSD 吞吐。",
      frontendHighlight: "高亮 SSD 冷层、DRAM/VRAM load、GPU sparse attention、KV block layout 和 scheduler。",
      frontendWarning: "dense attention 或 selected blocks 过多时 SSD I/O 会压倒计算。",
      highlightNodeIds: ["runtime", "state-layout", "ssd", "ddr", "dma", "accelerator", "hbm"],
    },
    layers: ["L2", "L3", "L8", "L10"],
    stateObjects: ["KV cache"],
    solves: "内存受限 PC 上长上下文 sparse attention 与 SSD 管理耦合。",
    approach: "coarse KV blocks、speculative prefetch、I/O orchestration，降低 KV footprint。",
    boundary: "适合 sparse attention/长上下文；dense attention 不一定同样收益。",
    akRelevance: "提示 A+K SSD 路线需要先确认 attention 稀疏性和块粒度。",
    evidence: ["references/papers/SolidAttention-FAST26.pdf"],
  },
  {
    id: "cacheslide",
    name: "CacheSlide",
    category: "prefix reuse",
    hardwarePath: ["prefix cache", "position-dependent attention", "runtime metadata"],
    topology: {
      summary: "面向 agent prompt 绝对位置漂移但相对顺序保持的场景，复用跨位置 KV 并用 SLIDE 管理 SSD spill。",
      primaryPath: ["agent prompt segments", "prefix/KV metadata", "position correction", "KV cache", "optional SSD spill"],
      hardwareClaims: ["runtime hash/metadata 查找 reused chunks", "attention 层做 weighted correction", "SLIDE manager 管理 KV load/update/eviction", "SSD 只在 memory pressure 下作为 spill 边界"],
      nonClaims: "不是普通 prefix cache，也不是 SSD direct I/O 论文。",
      criticalAssumption: "agent prompt template 可识别 reused/recompute chunks，位置编码校正保持精度。",
      frontendHighlight: "高亮 request、runtime/state-layout、HBM KV cache 和可选 SSD spill。",
      frontendWarning: "自由变化 prompt 或不支持的位置编码会削弱收益。",
      highlightNodeIds: ["request", "runtime", "ledger", "state-layout", "hbm", "ssd"],
    },
    layers: ["L3", "L10"],
    stateObjects: ["prefix", "KV cache"],
    solves: "agent workflow 中 prefix 位置变化导致 cache 不能直接复用。",
    approach: "relative-position-dependent caching 和 correction 机制。",
    boundary: "主要解决位置偏移下的 cache reuse，不解决底层 SSD/PCIe 瓶颈。",
    akRelevance: "适合进入 A+K prefix metadata 与 TTL 策略。",
    evidence: ["references/papers/CacheSlide.pdf"],
  },
  {
    id: "tutti",
    name: "Tutti",
    category: "SSD / direct object I/O",
    hardwarePath: ["HBM", "NVMe/SSD", "GPU direct/object I/O", "GPU io_uring", "DMA/stream"],
    topology: {
      summary: "把 SSD-backed KV 从 CPU-centric HBM-DRAM-SSD 改成 GPU-centric HBM-SSD KV object I/O，CPU 退出每次 I/O critical path。",
      primaryPath: ["HBM KV block", "GPU object I/O / gio_uring", "PCIe/P2P", "NVMe SSD"],
      hardwareClaims: ["HBM 中有 GPU file pool 和 SQ/CQ", "NVMe SSD 保存 KV object/file", "GPU io_uring 由 CPU 准备但 GPU issue/poll completion", "P2P mapping 将 KV block 映射到 SSD object"],
      nonClaims: "CPU 仍做 metadata 和异步准备，但不在单机 fast path 的数据/控制关键路径；远端 fallback 不是主线。",
      criticalAssumption: "需要 GPU/NPU 侧 storage submission、P2P mapping、I/O kernel 隔离和可预测 slack window。",
      frontendHighlight: "高亮 HBM/KV block -> GPU object I/O/gio_uring -> PCIe/P2P -> NVMe SSD；CPU 只作控制面说明。",
      frontendWarning: "A+K 迁移落在 P3，需要证明 NPU-native SSD/direct path；Tutti 正确证据是 arXiv 2605.03375。",
      highlightNodeIds: ["accelerator", "hbm", "state-layout", "dma", "ssd", "telemetry"],
    },
    layers: ["L3", "L4", "L8", "L11"],
    stateObjects: ["KV cache"],
    solves: "SSD-backed KV 被 tiny random I/O、CPU-centric GDS control path、DRAM-HBM copy 和 GPU stall 反噬。",
    approach: "GPU-native KV object store；GPU io_uring；slack-aware I/O scheduling；从 HBM 到 SSD 去 CPU critical path。",
    boundary: "对 Ascend 迁移的关键问题是是否有 NPU-native storage submission/direct path。",
    akRelevance: "是 A+K P3 NPU-native SSD/direct path 的重要对照。",
    evidence: ["references/papers/Tutti__arxiv-2605.03375.pdf"],
  },
  {
    id: "vllm-ascend-cpu-offload",
    name: "vLLM-Ascend KV Cache CPU Offload",
    category: "Ascend KV offload",
    hardwarePath: ["Ascend NPU memory", "CPU memory", "NPU D2H/H2D stream", "LRU block pool"],
    topology: {
      summary: "用 OffloadingConnector 和独立 NPU stream，把 inactive KV blocks 在 Ascend HBM 与 CPU memory 之间分层。",
      primaryPath: ["Ascend HBM active KV", "NPU D2H/H2D stream", "CPU memory LRU block pool", "runtime connector"],
      hardwareClaims: ["Ascend NPU memory 保存 active blocks", "CPU memory 承接 inactive KV", "独立 NPU stream 做 D2H/H2D", "LRU block pool 管理 CPU tier"],
      nonClaims: "不是 SSD/RDMA KV pool，也不等同 Tutti direct object I/O。",
      criticalAssumption: "copy 能与计算重叠，host memory 充足且 prefix/cache hit 率足够。",
      frontendHighlight: "高亮 Ascend/GPU HBM、PCIe/DMA stream、CPU DDR、runtime connector。",
      frontendWarning: "host OOM、copy stall 或低 prefix hit 会抵消容量收益。",
      highlightNodeIds: ["runtime", "accelerator", "hbm", "dma", "cpu", "ddr", "ledger"],
    },
    layers: ["L2", "L4", "L6", "L10"],
    stateObjects: ["KV cache"],
    solves: "NPU memory 不足时 inactive KV 无法容纳更多 context/concurrency。",
    approach: "OffloadingConnector + NPUOffloadingSpec；D2H/H2D 独立 NPU stream；CPU LRU block pool。",
    boundary: "host OOM、copy stall、prefix hit 率不足时收益有限。",
    akRelevance: "A+K P0 应优先跑通和量化这条路线。",
    evidence: ["references/web/vLLM-Ascend-KV-CPU-offload-live.html"],
  },
  {
    id: "vllm-ascend-ucm-kv-pool",
    name: "vLLM-Ascend UCM / KV Pool",
    category: "Ascend KV Pool / Mooncake",
    hardwarePath: ["Ascend HBM", "local DRAM", "SSD/NFS/3FS", "MooncakeConnectorV1", "remote H2D"],
    topology: {
      summary: "把 Ascend KV 从 HBM 扩展到 local DRAM、SSD/NFS/3FS 和 MooncakeConnectorV1 远端 KV Pool。",
      primaryPath: ["Ascend HBM", "local DRAM", "storage backend", "MooncakeConnectorV1", "remote H2D / KV Pool"],
      hardwareClaims: ["UCM external KV 提供 HBM->DRAM->storage backend", "KV Pool 通过 MooncakeConnectorV1/AscendStoreConnector 连接 P/D", "remote H2D 属于远端数据面", "SSD offload 是可测 cold tier"],
      nonClaims: "不是单一 CPU offload，也不代表所有 backend 默认有收益。",
      criticalAssumption: "fabric memory 对齐、buffer quota、TTL、failure policy 与 remote H2D 延迟可控。",
      frontendHighlight: "高亮 HBM、DRAM、SSD/storage、NIC/RDMA/Mooncake、runtime/ledger。",
      frontendWarning: "P1/P2 要分开验证 host pool、external KV、SSD backend 和远端 transfer。",
      highlightNodeIds: ["runtime", "ledger", "accelerator", "hbm", "ddr", "ssd", "nic", "remote"],
    },
    layers: ["L2", "L6", "L8", "L9", "L10"],
    stateObjects: ["KV cache", "prefix"],
    solves: "prefix cache 容量和持久化受设备内存限制，P/D KV pool 需要实际接口。",
    approach: "UCM external KV；HBM -> DRAM -> storage backend；MooncakeConnectorV1 + AscendStoreConnector；Mooncake SSD offload。",
    boundary: "fabric memory 对齐、buffer 大小、TTL、failure policy 和 remote H2D 需要工程验证。",
    akRelevance: "A+K P1/P2 的主路线，用来验证 host pool、external KV 和 SSD backend。",
    evidence: ["references/web/vLLM-Ascend-UCM-deployment-live.html", "references/web/vLLM-Ascend-KV-pool-live.html"],
  },
  {
    id: "dynamo",
    name: "NVIDIA Dynamo KVBM / LMCache / FlexKV",
    category: "工业 KV backend",
    hardwarePath: ["GPU memory", "CPU RAM", "disk", "NIXL transport", "KV-aware routing"],
    topology: {
      summary: "工业化 KV backend 把 GPU、CPU RAM、disk 和 NIXL transport 接到 KV-aware routing 与 LMCache/FlexKV 后端。",
      primaryPath: ["GPU memory", "CPU RAM", "disk tier", "NIXL transport", "KV-aware routing"],
      hardwareClaims: ["GPU memory 是 hot tier", "CPU RAM/disk 是 offload backend", "NIXL transport 支持 aggregated/disaggregated deployment", "routing 层感知 KV locality"],
      nonClaims: "NVIDIA/CUDA 生态证据不能直接证明 Ascend 可行。",
      criticalAssumption: "backend 与 routing 能把 KV hit、transfer 和 engine scheduling 对齐。",
      frontendHighlight: "高亮 HBM、CPU RAM、disk、NIXL/RDMA 和 runtime routing。",
      frontendWarning: "只能作为 A+K KV backend 抽象对标，不能直接外推性能。",
      highlightNodeIds: ["runtime", "ledger", "accelerator", "hbm", "ddr", "ssd", "nic", "remote"],
    },
    layers: ["L2", "L8", "L9", "L10"],
    stateObjects: ["KV cache"],
    solves: "工业化 vLLM serving 需要统一 KV offload backend 与 KV-aware routing。",
    approach: "KVBM 三层架构、CPU/disk tiers、LMCache/FlexKV backend、aggregated/disaggregated deployment。",
    boundary: "CUDA/NVIDIA 生态证据不能直接推导 Ascend；但 data-plane 抽象值得对标。",
    akRelevance: "给 A+K 的 KV backend 抽象和路由策略提供参照。",
    evidence: ["references/web/NVIDIA-Dynamo-KV-offloading-live.html"],
  },
  {
    id: "servegen",
    name: "ServeGen",
    category: "workload 与仿真",
    hardwarePath: ["workload trace", "simulator input", "per-client characterization"],
    topology: {
      summary: "提供 production-scale LLM serving workload characterization 和 per-client generation，作为仿真与评测输入。",
      primaryPath: ["request arrival", "client decomposition", "prompt/output length", "workload generator", "simulator input"],
      hardwareClaims: ["刻画 arrival、length、conversation、multimodal/reasoning workload", "驱动 vLLM/SGLang 或仿真器评估", "影响 provisioning 和 P/D ratio 评估"],
      nonClaims: "不改硬件数据面，不提供 operator/hardware latency 模型。",
      criticalAssumption: "生成 workload 的 client/time/length 分布能覆盖目标部署场景。",
      frontendHighlight: "只高亮 request/workload 与 telemetry/simulator，不高亮 GPU/CPU/SSD 主数据面。",
      frontendWarning: "它决定评测是否真实，但不能单独证明某条 offload 路径有效。",
      highlightNodeIds: ["request", "runtime", "telemetry"],
    },
    layers: ["L0", "L11"],
    stateObjects: ["workload"],
    solves: "synthetic workload 不真实，导致仿真器结论无法落地。",
    approach: "per-client workload characterization/generation。",
    boundary: "不解决硬件模型本身，但决定仿真 workload 可信度。",
    akRelevance: "为 A+K 仿真器提供真实 arrival/reuse/长度分布输入。",
    evidence: ["references/papers/ServeGen-NSDI26.pdf"],
  },
  {
    id: "profinfer",
    name: "ProfInfer",
    category: "可观测与瓶颈定位",
    hardwarePath: ["runtime timeline", "counters", "queue", "copy", "I/O"],
    topology: {
      summary: "非侵入式 eBPF profiler，把 token、graph、operator、scheduler、PMC trace 对齐为瓶颈诊断 timeline。",
      primaryPath: ["Telemetry / tracer", "runtime probes", "CPU/GPU/NPU backend", "scheduler events", "hardware counters"],
      hardwareClaims: ["采集 token/graph/operator 级 trace", "观察 CPU scheduler 事件", "读取 PMC counters", "可看到 backend partition 与 stalls"],
      nonClaims: "不是调度或 offload 机制，不直接优化 SSD/RDMA 数据面。",
      criticalAssumption: "probe 点、counter 来源和 Ascend/CANN profiler 能对齐。",
      frontendHighlight: "用灰色观测路径高亮 Telemetry -> Runtime -> backend。",
      frontendWarning: "eBPF 适合 runtime/CPU 可见性，NPU 内部 stream/HBM/copy counter 还需 CANN/Ascend profiler。",
      highlightNodeIds: ["telemetry", "runtime", "accelerator", "cpu"],
    },
    layers: ["L10", "L11"],
    stateObjects: ["telemetry"],
    solves: "端到端延迟无法分解到算子、队列、拷贝、I/O。",
    approach: "timeline/counter 对齐，定位 bottleneck。",
    boundary: "需要和 Ascend/CANN counters 对齐。",
    akRelevance: "A+K 需要把瓶颈验证和规格反推落到类似字段。",
    evidence: ["references/papers/ProfInfer__arxiv-2601.20755.pdf"],
  },
  {
    id: "llmservingsim2",
    name: "LLMServingSim2.0",
    category: "仿真器与规格反推",
    hardwarePath: ["heterogeneous hardware", "memory/network/power model", "operator profiler", "prefix cache manager"],
    topology: {
      summary: "统一系统级仿真器，把 workload、operator profile、异构硬件、多级内存、P/D、MoE、prefix cache 和 power 放进 runtime-driven loop。",
      primaryPath: ["workload", "telemetry / simulator", "accelerator model", "CPU/memory model", "network/storage/power model"],
      hardwareClaims: ["建模 heterogeneous devices", "显式模拟 device/host/storage/CXL memory", "建模 KV movement 与 network contention", "输出 latency、throughput、power"],
      nonClaims: "不是具体 offload 策略，也不替代真实 A+K hardware profile。",
      criticalAssumption: "operator、memory、interconnect 和 workload profile 足够准确。",
      frontendHighlight: "用灰色观测/仿真路径连接 request、telemetry、accelerator、CPU、memory、network、storage。",
      frontendWarning: "没有 Ascend/Kunpeng 本地 profile 时不能输出规格结论。",
      highlightNodeIds: ["request", "telemetry", "runtime", "accelerator", "hbm", "cpu", "ddr", "ssd", "nic", "remote"],
    },
    layers: ["L0", "L1", "L2", "L7", "L9", "L11"],
    stateObjects: ["workload", "KV cache", "MoE expert", "telemetry"],
    solves: "传统仿真器难覆盖异构硬件、MoE、prefix cache、P/D 和 offload。",
    approach: "trace-driven operator profiler；heterogeneous instances；MoE expert offloading；prefix cache manager；memory/power/system simulator。",
    boundary: "迁移到 Ascend/Kunpeng 仍需硬件 profile。",
    akRelevance: "是 A+K 瓶颈验证 / 规格反推的仿真器对照。",
    evidence: ["references/papers/LLMServingSim-2.0__arxiv-2602.23036.pdf"],
  },
  {
    id: "burstgpt",
    name: "BurstGPT",
    category: "workload 与 burst trace",
    hardwarePath: ["arrival trace", "burst workload", "simulator input"],
    topology: {
      summary: "真实 LLM serving trace/benchmark，用 burstiness、request/response length、conversation 和 failure 行为驱动压力测试。",
      primaryPath: ["arrival trace", "burst workload", "conversation / token lengths", "benchmark replay", "simulator input"],
      hardwareClaims: ["提供 timestamp/RPS/CV/burstiness", "提供 request/response tokens 与 conversation interval", "可用于 PD ratio 和 provisioning 仿真", "暴露 latency jitter 与 failure risk"],
      nonClaims: "不是硬件机制，不能单独给出 CPU/GPU/SSD 规格。",
      criticalAssumption: "trace 能代表目标业务的 burst、长尾和会话模式。",
      frontendHighlight: "只高亮 request/workload -> telemetry/simulator。",
      frontendWarning: "云端 GPT trace 未必覆盖本地 coding agent 或 A+K 私有负载，需要再校准。",
      highlightNodeIds: ["request", "runtime", "telemetry"],
    },
    layers: ["L0"],
    stateObjects: ["workload"],
    solves: "平均负载不能解释 burst、队列长尾和 SLO 压力。",
    approach: "提供 burst workload trace，用于 replay 和压力测试。",
    boundary: "只提供 workload 线索，不解决硬件数据面。",
    akRelevance: "适合进入 A+K 仿真器 workload 合成和压力场景。",
    evidence: ["references/papers/BurstGPT__arxiv-2401.17644.pdf"],
  },
];

export const stateObjects: StateObject[] = [
  {
    name: "KV cache",
    growth: "context length、batch、concurrency、layers",
    tiers: ["HBM hot", "CPU DRAM warm", "SSD/remote cold"],
    works: ["mooncake", "lmcache-ucm", "tutti", "bidaw", "vllm-ascend-cpu-offload", "vllm-ascend-ucm-kv-pool"],
    hardwareAction: "block 化、prefix reuse、HBM/DRAM/SSD 分层、restore/recompute。",
  },
  {
    name: "MoE expert",
    growth: "expert count、hidden size、precision、routing skew",
    tiers: ["GPU hot experts", "CPU warm experts", "SSD cold experts"],
    works: ["ktransformers", "finemoe", "dali", "fluxmoe"],
    hardwareAction: "hot experts 常驻，warm experts 放 CPU/DRAM，cold experts 放 SSD/remote。",
  },
  {
    name: "weights",
    growth: "模型参数规模、量化策略、layer-wise load",
    tiers: ["HBM resident", "CPU compute/offload", "storage checkpoint"],
    works: ["flexinfer", "ktransformers"],
    hardwareAction: "layer-wise load、CPU compute、expert offload。",
  },
  {
    name: "activation / workspace",
    growth: "batch、sequence、attention kernel workspace",
    tiers: ["NPU/GPU SRAM", "HBM workspace", "recompute"],
    works: ["llm-npu", "solidattention"],
    hardwareAction: "chunking、sparse attention、workspace reuse。",
  },
  {
    name: "prefix / radix metadata",
    growth: "session reuse、agent workflow、position shift",
    tiers: ["runtime index", "external KV", "persistent metadata"],
    works: ["cacheslide", "llmservingsim2", "lmcache-ucm"],
    hardwareAction: "prefix index、position correction、TTL、external KV。",
  },
];

export const akStages: AkStage[] = [
  {
    id: "P0",
    title: "NPU HBM + CPU DRAM warm tier",
    goal: "跑通 vLLM-Ascend KV Cache CPU Offload，建立最小可测闭环。",
    actions: ["记录 NPU HBM occupancy", "记录 CPU DDR / pinned memory", "记录 D2H/H2D overlap", "记录 prefix hit/miss"],
    risk: "host OOM、copy stall、prefix hit 率不足会抵消扩容收益。",
  },
  {
    id: "P1",
    title: "UCM / KV Pool / MooncakeConnectorV1",
    goal: "验证 P/D、external KV、Mooncake transfer 和 host memory pool。",
    actions: ["接入 UCM external KV", "验证 MooncakeConnectorV1", "量化 remote H2D", "建立 object lifecycle 字段"],
    risk: "fabric memory alignment、buffer quota、routing policy 会成为工程前置条件。",
  },
  {
    id: "P2",
    title: "SSD / NFS / 3FS cold tier",
    goal: "验证 Mooncake SSD offload / UCM storage backend 的真实收益边界。",
    actions: ["测 I/O 粒度", "测 buffer 对齐", "测 SSD quota", "记录 KV load failure"],
    risk: "tiny random I/O、CPU control path、DRAM-HBM bounce copy 可能反噬。",
  },
  {
    id: "P3",
    title: "NPU-native SSD/direct path",
    goal: "形成硬件/运行时创新点，而不是只做容量外溢。",
    actions: ["定义 NPU-side async storage submission", "对标 Tutti GPU-native object I/O", "建模 direct path 与 bounce path 差异"],
    risk: "公开证据不足，需要用原型和硬件 profile 证明。",
  },
];

export const simulatorModules: SimulatorModule[] = [
  { name: "workload", fields: ["request_id", "arrival_time", "prompt_tokens", "output_tokens", "session_id", "prefix_id", "reuse_distance", "SLO"] },
  { name: "model", fields: ["layers", "hidden_size", "heads", "GQA/MQA", "KV bytes/token", "MoE expert count", "top-k", "precision"] },
  { name: "accelerator", fields: ["device_type", "HBM capacity", "HBM bandwidth", "operator latency by shape", "stream count", "copy engine", "power curve"] },
  { name: "CPU", fields: ["cores", "ISA", "NUMA sockets", "DDR bandwidth", "kernel latency by shape", "pinned memory capacity", "package power"] },
  { name: "interconnect", fields: ["link_type", "bandwidth", "latency", "setup_cost", "P2P capability", "congestion model"] },
  { name: "storage", fields: ["tier_type", "capacity", "seq/random bandwidth", "IOPS", "I/O size distribution", "queue depth", "submit path", "buffer alignment"] },
  { name: "state object", fields: ["object_type", "bytes", "layer", "tier", "hotness", "next_use_time", "load_cost", "evict_cost", "recompute_cost", "consistency_scope"] },
  { name: "scheduler", fields: ["queue_state", "policy_decision", "cache_hit_layer", "offload_ratio", "prefetch_lead_time", "eviction_reason"] },
  { name: "telemetry", fields: ["TTFT", "TPOT", "P95/P99", "throughput", "goodput", "stall_reason", "energy/token", "simulation_error"] },
];

export const glmModelFacts: GlmModelFact[] = [
  { label: "Model", value: "744B MoE", detail: "glm_moe_dsa, active params about 39B-40B" },
  { label: "Depth", value: "78 layers", detail: "Layer 0-2 dense MLP; layer 3-77 sparse MoE" },
  { label: "Hidden", value: "6144", detail: "Transformer residual width; dense MLP intermediate size 12288" },
  { label: "Context", value: "1M context", detail: "MLA compressed KV plus DSA / IndexShare" },
  { label: "Experts", value: "256 routed / top-8", detail: "1 shared expert is always on the hot path" },
  { label: "KV latent", value: "512 + 64 = 576", detail: "kv_lora_rank plus qk_rope_head_dim as a system-level cache width anchor" },
];

export const glmComponents: GlmComponent[] = [
  {
    id: "runtime",
    title: "CPU runtime",
    layerScope: "Before model and between decode steps",
    hardwareOwner: "CPU runtime",
    prefill: "Tokenization, chat template, position ids, attention mask, request batching and prefix lookup are prepared before dispatching the prompt.",
    decode: "Continuous batching, sampler, stop checks and cache metadata decide which sessions keep decoding and which state objects should be prefetched.",
    bottleneck: "Queueing, cache miss decisions and metadata contention can hide as model latency even when accelerator kernels are fast.",
    akMove: "Kunpeng should own metadata, prefix lookup, prefetch planning and trace collection, while keeping the model hot path on Ascend.",
  },
  {
    id: "embedding",
    title: "Embedding",
    layerScope: "Input and every decode token",
    hardwareOwner: "GPU/NPU + HBM",
    prefill: "Prompt token ids are gathered from the embedding table into the 6144-wide residual stream.",
    decode: "Only the current token is embedded, so kernel launch and memory access overhead matter more than large-matrix throughput.",
    bottleneck: "The table is hot model state and should not cross DDR or SSD during the serving loop.",
    akMove: "Keep embedding weights resident near Ascend HBM/NPU memory; CPU only provides ids and position metadata.",
  },
  {
    id: "rmsnorm",
    title: "RMSNorm / RoPE / residual",
    layerScope: "Every Transformer block",
    hardwareOwner: "GPU/NPU + HBM",
    prefill: "Elementwise normalization, RoPE position handling and residual adds run over the full prompt sequence.",
    decode: "The same elementwise path runs on a single token and is sensitive to launch overhead and stream synchronization.",
    bottleneck: "These operators are not the capacity driver, but they can amplify synchronization stalls between attention and expert paths.",
    akMove: "Keep the path fused or near-fused on Ascend; use CPU only for metadata and profiler attribution.",
  },
  {
    id: "mla-dsa",
    title: "MLA / DSA / IndexShare attention",
    layerScope: "All 78 layers",
    hardwareOwner: "GPU/NPU + HBM",
    prefill: "Q low-rank projection, compressed KV projection, RoPE, DSA full indexer or IndexShare reuse, then sparse attention over selected prompt blocks.",
    decode: "For the current token, the path reads historical compressed KV, selects or reuses sparse indexes and computes attention over selected history.",
    bottleneck: "Prefill stresses attention kernels and workspace; decode stresses KV bandwidth, sparse gather and index metadata.",
    akMove: "Ascend remains the primary owner; NEO-like experiments should touch only selected decode attention subpaths when overlap is measurable.",
  },
  {
    id: "kv-cache",
    title: "Compressed KV cache",
    layerScope: "All attention layers",
    hardwareOwner: "GPU/NPU + HBM / CPU DDR",
    prefill: "Prompt KV is written into paged cache blocks, with compressed KV width anchored by kv_lora_rank plus RoPE position state.",
    decode: "Every new token reads historical compressed KV and appends its current KV, making cache bandwidth and block metadata central to TPOT.",
    bottleneck: "HBM capacity is shared with weights, activation, workspace and expert cache; long context turns KV into a scheduling object.",
    akMove: "Use Kunpeng DDR as KV warm tier only when restore or CPU-side attention can be hidden behind Ascend work.",
  },
  {
    id: "dense-mlp",
    title: "Dense MLP",
    layerScope: "Layer 0-2",
    hardwareOwner: "GPU/NPU + HBM",
    prefill: "Dense SwiGLU-style gate/up/down projections run as large GEMMs on the full prompt.",
    decode: "Small GEMMs run per token and can underutilize accelerator cores at low batch.",
    bottleneck: "It is compute-heavy but only covers the first 3 layers, so it is not the main GLM-5.2 capacity pressure.",
    akMove: "Keep dense MLP on Ascend; do not spend CPU offload complexity on this narrow segment first.",
  },
  {
    id: "moe-router",
    title: "MoE router",
    layerScope: "Layer 3-77",
    hardwareOwner: "GPU/NPU + HBM",
    prefill: "Router scores 256 routed experts for prompt tokens and selects top-8 per token before expert dispatch.",
    decode: "Router selects top-8 for the current token and exposes expert ids that drive hit/miss and prefetch decisions.",
    bottleneck: "Router math is smaller than expert compute, but its decisions determine expert locality and tail latency.",
    akMove: "Run router on Ascend; stream expert ids, hit/miss and load bytes into Kunpeng-side trace and prefetch policy.",
  },
  {
    id: "shared-expert",
    title: "Shared expert",
    layerScope: "Layer 3-77",
    hardwareOwner: "GPU/NPU + HBM",
    prefill: "The shared expert is active for each token, so it behaves like a hot FFN path.",
    decode: "It stays on the per-token critical path and should not depend on CPU or SSD availability.",
    bottleneck: "Moving it away from HBM would add synchronization to the most predictable expert path.",
    akMove: "Pin shared expert and other hot experts near Ascend; treat them as non-negotiable hot state.",
  },
  {
    id: "routed-experts",
    title: "Routed experts",
    layerScope: "Layer 3-77",
    hardwareOwner: "GPU/NPU + HBM / CPU DDR / SSD cold tier",
    prefill: "Prompt tokens are grouped by top-8 expert choices; hot routed experts execute near the accelerator while colder experts create placement pressure.",
    decode: "Each token may hit or miss a hot expert set; a miss can force CPU DDR, SSD or remote recovery into the tail of TPOT.",
    bottleneck: "Expert weight volume, hit rate, prefetch lead time and CPU expert kernel quality dominate the MoE pressure surface.",
    akMove: "Use KTransformers-like expert warm tier cautiously: Ascend keeps shared/hot experts, Kunpeng DDR holds warm experts, SSD holds cold experts.",
  },
  {
    id: "lm-head",
    title: "lm_head / sampler",
    layerScope: "After final norm",
    hardwareOwner: "GPU/NPU + HBM",
    prefill: "Usually only the last prompt position needs logits for the first generated token.",
    decode: "Every step produces logits, then sampler or MTP acceptance decides whether generation continues.",
    bottleneck: "The output projection is a large matrix and sampler synchronization can become visible at small batch.",
    akMove: "Keep lm_head on Ascend; CPU can handle sampling policy when the transfer is cheap and already overlapped.",
  },
];

export const glmFlowSteps: GlmFlowStep[] = [
  {
    phase: "prefill",
    order: 1,
    title: "Prefill request preparation",
    hardware: "CPU runtime",
    summary: "Chat template, tokenization, position ids, attention mask, prefix hit lookup and batch assembly happen before model dispatch.",
    componentIds: ["runtime"],
    risk: "Bad prefix/cache policy repeats long prefill and increases TTFT.",
  },
  {
    phase: "prefill",
    order: 2,
    title: "Embedding and residual stream",
    hardware: "GPU/NPU + HBM",
    summary: "Prompt ids become [B,S,6144] hidden states through embedding lookup.",
    componentIds: ["embedding", "rmsnorm"],
    risk: "Hot weights and activation start occupying HBM before attention and MoE workspace arrive.",
  },
  {
    phase: "prefill",
    order: 3,
    title: "MLA projections and IndexShare",
    hardware: "GPU/NPU + HBM",
    summary: "Q low-rank, compressed KV and RoPE state are produced; DSA full indexer or IndexShare metadata selects sparse attention blocks.",
    componentIds: ["mla-dsa", "kv-cache"],
    risk: "Attention workspace, sparse index metadata and KV writes compete for HBM bandwidth.",
  },
  {
    phase: "prefill",
    order: 4,
    title: "Dense layers 0-2",
    hardware: "GPU/NPU + HBM",
    summary: "The first three layers use dense MLP, giving large GEMM work that suits accelerator cores.",
    componentIds: ["dense-mlp"],
    risk: "Compute is heavy but not the dominant model-wide placement issue.",
  },
  {
    phase: "prefill",
    order: 5,
    title: "MoE layers 3-77",
    hardware: "GPU/NPU + HBM",
    summary: "Router selects top-8 routed experts; shared expert and hot routed experts execute and combine back into residual state.",
    componentIds: ["moe-router", "shared-expert", "routed-experts"],
    risk: "Large prompt groups can reveal expert cache pressure and dispatch imbalance.",
  },
  {
    phase: "prefill",
    order: 6,
    title: "KV commit and first logits",
    hardware: "GPU/NPU + HBM + CPU runtime",
    summary: "Prompt KV blocks are committed, final norm and lm_head produce logits, and runtime prepares the first decode step.",
    componentIds: ["kv-cache", "lm-head", "runtime"],
    risk: "Fragmented KV blocks and sampler synchronization show up as TTFT tail.",
  },
  {
    phase: "decode",
    order: 1,
    title: "Decode batch formation",
    hardware: "CPU runtime",
    summary: "Runtime merges active sessions, handles accepted draft tokens or stop checks, and sets cache metadata for the next token.",
    componentIds: ["runtime"],
    risk: "Scheduler and metadata stalls can dominate when per-token compute is small.",
  },
  {
    phase: "decode",
    order: 2,
    title: "Current token embedding",
    hardware: "GPU/NPU + HBM",
    summary: "Only the new token enters the residual stream, so launch overhead and stream ordering become visible.",
    componentIds: ["embedding", "rmsnorm"],
    risk: "Small batch decode can leave accelerator cores underutilized.",
  },
  {
    phase: "decode",
    order: 3,
    title: "Read KV cache and sparse attention",
    hardware: "GPU/NPU + HBM, optional CPU DDR warm tier",
    summary: "The token reads historical compressed KV, uses DSA or IndexShare metadata and runs sparse attention over selected history.",
    componentIds: ["mla-dsa", "kv-cache"],
    risk: "This is where NEO-like KV warm tier can help or hurt, depending on CPU attention bandwidth and overlap.",
  },
  {
    phase: "decode",
    order: 4,
    title: "Append current KV",
    hardware: "GPU/NPU + HBM",
    summary: "The current token KV is appended to paged cache while block tables stay consistent with runtime metadata.",
    componentIds: ["kv-cache"],
    risk: "KV block allocation, fragmentation and restore timing affect TPOT and P99.",
  },
  {
    phase: "decode",
    order: 5,
    title: "Router and experts",
    hardware: "GPU/NPU + HBM, CPU DDR for warm experts",
    summary: "Router emits top-8 ids; shared and hot experts stay near HBM while warm routed experts may be prefetched or executed off hot path.",
    componentIds: ["moe-router", "shared-expert", "routed-experts"],
    risk: "KTransformers-like paths depend on expert hit rate, NUMA locality and CPU kernel quality.",
  },
  {
    phase: "decode",
    order: 6,
    title: "Logits and sampling",
    hardware: "GPU/NPU + HBM + CPU runtime",
    summary: "Final norm and lm_head produce logits; sampler selects or accepts tokens and loops until stop.",
    componentIds: ["lm-head", "runtime"],
    risk: "Frequent host synchronization or unhidden sampling transfer increases per-token latency.",
  },
];

export const glmPathComparisons: GlmPathComparison[] = [
  {
    id: "standard-gpu",
    title: "标准纯 GPU/NPU",
    mainCompute: "Embedding, MLA/DSA attention, dense MLP, router, experts and lm_head all run on GPU/NPU.",
    statePlacement: "Weights, compressed KV, activation, workspace, IndexShare metadata and hot experts are pushed into HBM/NPU memory.",
    cpuRole: "Tokenizer, scheduler, sampler, cache metadata and host staging; CPU is not in the per-token compute hot path.",
    benefit: "Shortest hot path and mature serving stack.",
    risk: "HBM is squeezed by weights, KV, experts, activation and workspace; decode becomes bandwidth or scheduler bound.",
    changedComponents: ["runtime", "mla-dsa", "kv-cache", "routed-experts"],
  },
  {
    id: "neo",
    title: "NEO-like KV / decode attention",
    mainCompute: "GPU/NPU keeps prefill, projections, MoE, lm_head and most attention work.",
    statePlacement: "Some request KV stays in CPU DDR, and the paired decode attention subpath runs on CPU instead of moving full KV back.",
    cpuRole: "KV warm tier, selected decode attention compute and load-aware scheduling.",
    benefit: "Reduces GPU HBM KV pressure and can expand batch or concurrency when overlap succeeds.",
    risk: "CPU attention kernel, DDR bandwidth and D2H/H2D synchronization can become the new TPOT bottleneck.",
    changedComponents: ["runtime", "mla-dsa", "kv-cache"],
  },
  {
    id: "ktransformers",
    title: "KTransformers-like MoE expert tiering",
    mainCompute: "GPU/NPU keeps attention, router, shared expert, hot experts and non-expert backbone.",
    statePlacement: "Routed experts are tiered across HBM hot set, CPU DDR warm set and SSD cold set.",
    cpuRole: "Expert warm tier, expert task queue, optional CPU expert execution and prefetch planning.",
    benefit: "Directly targets GLM-5.2's large MoE expert weight pressure.",
    risk: "Kunpeng SVE/SME expert kernels, NUMA placement and synchronization must be measured instead of inherited from x86 AMX results.",
    changedComponents: ["moe-router", "shared-expert", "routed-experts"],
  },
];

export const glmTraceFields = [
  "layer_id",
  "layer_type",
  "indexer_type",
  "q_proj_latency",
  "kv_proj_latency",
  "indexer_latency",
  "attention_latency",
  "kv_read_bytes",
  "kv_write_bytes",
  "router_latency",
  "topk_expert_ids",
  "expert_hit_or_miss",
  "expert_load_bytes",
  "expert_compute_latency",
  "residual_norm_latency",
  "hbm_occupancy",
  "ddr_traffic",
  "dma_bytes",
  "stall_reason",
];

export const layerIds: LayerId[] = ["L0", "L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8", "L9", "L10", "L11"];

export const sourceDocument = "../大模型推理硬件层面对照地图.md";
