from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_DIR = REPO_ROOT / "工作记录与进度笔记本" / "p1_inference_contracts"
BASE_MANIFEST = CONTRACT_DIR / "workload_manifest.yaml"
LONG_MANIFEST = CONTRACT_DIR / "workload_long_manifest.yaml"
LONG_PROMPT_DIR = CONTRACT_DIR / "prompts_long"

CHAR_PER_TARGET_TOKEN = 4.8


def _load_yaml(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return data


def _dump_yaml(path: Path, data: dict[str, Any]) -> None:
    path.write_text(
        yaml.safe_dump(data, sort_keys=False, allow_unicode=False, width=120),
        encoding="utf-8",
    )


def _context_block(label: str, index: int, scenario: str) -> str:
    return f"""
### Static Context Block {index:04d} - {label}

Server evidence summary:
- run_id: synthetic_materialized_context_{label}_{index:04d}
- evidence boundary: static text fixture, not live command output
- model path under test: /data/node0_disk1/Public/Qwen3.5-4B
- profiler policy: torch_profiler_trace_candidate_only
- CANN timeline policy: do not claim device timeline pairing without aligned join keys

Representative tool output:
```text
[request {index:04d}] enqueue_ns=100000{index:04d}
[request {index:04d}] prefill_start_ns=100100{index:04d}
[request {index:04d}] decode_start_ns=100900{index:04d}
[npu] device=npu:6 hbm_used_gb=18.{index % 10} ai_core_util_pct={40 + index % 50}
[copy] object_id=kv:req_{index:04d}:L00 direction=h2d bytes={1048576 + index * 4096}
[queue] batch_id=batch_{index // 4:04d} queue_wait_us={200 + index * 7}
```

Representative code excerpt:
```python
def record_stage_{index:04d}(event_writer, request_id, phase, timestamp_ns):
    event_writer.write({{
        "trace_id": "trace_materialized_{label}",
        "request_id": request_id,
        "phase": phase,
        "timestamp_ns": timestamp_ns,
        "resource_scope": "request_runtime_profile",
        "policy_decision": "static_fixture_only",
    }})
```

Reasoning note:
The analysis must separate queue wait, prompt tokenization, prefill forward time,
decode step time, state-object movement, and profiler alignment. A slow token can
only be attributed to copy, KV restore, expert miss, CPU scheduling, HBM pressure,
or NPU compute when the request id, phase, object id, stream id, and timestamp
base are all present in the same evidence chain. The current block repeats this
constraint intentionally so the prompt has stable long-context pressure while
remaining deterministic and reviewable.
"""


def _build_repeated_context(label: str, scenario: str, target_chars: int) -> str:
    blocks: list[str] = []
    index = 1
    while len("\n".join(blocks)) < target_chars:
        blocks.append(_context_block(label, index, scenario))
        index += 1
    return "\n".join(blocks)


def _target_chars(prompt: dict[str, Any]) -> int:
    estimated_tokens = int(prompt["estimated_prompt_tokens"])
    return max(1600, int(estimated_tokens * CHAR_PER_TARGET_TOKEN))


def _build_prompt_text(prompt: dict[str, Any], base_text: str) -> str:
    prompt_id = str(prompt["prompt_id"])
    scenario = str(prompt["scenario"])
    target_chars = _target_chars(prompt)
    header = f"""# {prompt_id} Materialized Long Context

This is a deterministic static prompt fixture generated by
`tools/inference_contracts/materialize_long_prompts.py`.

It is not live server output. It does not ask the model to call tools. It keeps
the original short fixture as the task seed, then adds static coding-agent-like
context blocks so the server tokenizer can calibrate real long-context buckets.

Target bucket: {prompt["context_len_bucket"]}
Target prompt tokens from base manifest: {prompt["estimated_prompt_tokens"]}
Scenario: {scenario}

## Original Short Fixture

{base_text.strip()}

## Materialized Static Context
"""
    task = f"""
## Final Task

Using only the static context above, answer the original task for {prompt_id}.
Keep the response concise and evidence-bound. Do not invent live measurements,
do not claim CANN device timeline pairing, and do not make performance or
bottleneck conclusions beyond what the supplied static text can support.
"""
    if prompt_id in {"P007", "P008"}:
        shared_chars = max(1200, int(int(prompt["shared_prefix_tokens"]) * CHAR_PER_TARGET_TOKEN))
        shared_prefix = _build_repeated_context("prefix_group_a_shared", scenario, shared_chars)
        unique_chars = max(800, target_chars - len(shared_prefix))
        unique_suffix = _build_repeated_context(f"{prompt_id}_unique_suffix", scenario, unique_chars)
        return (
            header
            + "\n### Shared Prefix Group A\n"
            + shared_prefix
            + "\n\n### Unique Request Tail\n"
            + unique_suffix
            + task
        )
    return header + _build_repeated_context(prompt_id, scenario, target_chars) + task


def materialize() -> None:
    base_manifest = _load_yaml(BASE_MANIFEST)
    prompts = base_manifest.get("prompts", [])
    if not isinstance(prompts, list):
        raise ValueError("base manifest prompts must be a list")

    LONG_PROMPT_DIR.mkdir(parents=True, exist_ok=True)
    (LONG_PROMPT_DIR / "README.md").write_text(
        "# Materialized Long Prompt Fixtures\n\n"
        "Generated by `tools/inference_contracts/materialize_long_prompts.py`.\n"
        "These files are static text fixtures for tokenizer calibration and later "
        "bounded long-context smoke tests. They are not live server logs.\n",
        encoding="utf-8",
    )

    long_prompts: list[dict[str, Any]] = []
    for prompt in prompts:
        if not isinstance(prompt, dict):
            raise ValueError("prompt entries must be mappings")
        prompt_id = str(prompt["prompt_id"])
        base_prompt_path = str(prompt["prompt_path"])
        base_text = (CONTRACT_DIR / base_prompt_path).read_text(encoding="utf-8")
        long_prompt_path = LONG_PROMPT_DIR / f"{prompt_id}.md"
        long_text = _build_prompt_text(prompt, base_text)
        long_prompt_path.write_text(long_text, encoding="utf-8")

        long_prompt = dict(prompt)
        long_prompt["base_prompt_path"] = base_prompt_path
        long_prompt["prompt_path"] = f"prompts_long/{prompt_id}.md"
        long_prompt["materialization_policy"] = "deterministic_static_blocks"
        long_prompt["materialized_target_tokens"] = int(prompt["estimated_prompt_tokens"])
        long_prompt["materialized_char_count"] = len(long_text)
        long_prompt["shape_fixture_measured_prompt_tokens_qwen3_5_4b"] = prompt.get(
            "measured_prompt_tokens_qwen3_5_4b"
        )
        long_prompt["measured_prompt_tokens_qwen3_5_4b"] = None
        long_prompts.append(long_prompt)

    long_manifest = {
        "schema_name": "workload_long_manifest",
        "schema_version": "0.1.0",
        "source": "materialized_static_prompt_fixtures",
        "base_manifest": "workload_manifest.yaml",
        "generator": "tools/inference_contracts/materialize_long_prompts.py",
        "token_policy": "server_tokenizer_calibration_required",
        "token_calibration": {
            "status": "pending_server_calibration",
            "planned_run_id": "runtime_long_prompt_calibration_2026_0706_p1_012",
            "model_path": "/data/node0_disk1/Public/Qwen3.5-4B",
            "tokenizer_class": "pending_server_report",
        },
        "prompts": long_prompts,
    }
    _dump_yaml(LONG_MANIFEST, long_manifest)


if __name__ == "__main__":
    materialize()
