#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
export P8_2_K1A_TASK_ID=p8_2_k1a_r3_r2_r2_deepseek_v4_flash_forensic_replay_2026_0720
export P8_2_K1A_EXECUTION_MODE=authorized_parent_forensics_source_semantics_and_conditional_same_capacity_single_lifecycle
export P8_2_K1A_EXPECTED_COMMAND_SHA256=8301f4c4c4f203e42f7954e4e4c9b961b55725b132dcbd6fb4b8625bc271bde6
export P8_2_K1A_REPO_FILE_LIST=benchmarks/deepseek_v4_flash/p8_2_k1a_simple_cpu_offload_feasibility_audit.yaml:benchmarks/deepseek_v4_flash/p8_2_k1a_r3_formal_lifecycle_audit.yaml:benchmarks/deepseek_v4_flash/p8_2_k1a_r3_r2_r1_installed_source_gate_audit.yaml:benchmarks/deepseek_v4_flash/p8_2_k1a_r3_r2_r2_forensic_replay_audit.yaml:benchmarks/deepseek_v4_flash/workloads/p8_2_k1a_r3_simple_cpu_offload_store_restore.yaml:benchmarks/deepseek_v4_flash/workloads/p8_2_k1a_r3_r2_r2_forensic_replay.yaml:tools/inference_contracts/audit_deepseek_p8_2_k1a_simple_cpu_offload.py:tools/inference_contracts/canonicalize_server_argv.py:tools/inference_contracts/p8_2_k1a_failure_forensics.py:tools/inference_contracts/p8_2_k1a_simple_cpu_offload_observer.py:tools/inference_contracts/run_deepseek_p8_2_k1a_simple_cpu_offload.py:tools/inference_contracts/run_deepseek_p8_2_k1a_simple_cpu_offload_mode.sh:tools/inference_contracts/run_deepseek_p8_2_k1a_simple_cpu_offload.sh:tools/inference_contracts/run_deepseek_p8_2_k1a_r3_simple_cpu_offload.sh:tools/inference_contracts/run_deepseek_p8_2_k1a_r3_r2_r2_simple_cpu_offload.sh:benchmarks/deepseek_v4_flash/patches/vllm_ascend_v0221rc1_simple_cpu_offload_observer_overlay.patch
export P8_2_K1A_CANDIDATE_GREEN=candidate_green_p8_2_k1a_r3_r2_r2_simple_cpu_offload_store_restore
export P8_2_K1A_NO_SUCCESS_GRADE=red_p8_2_k1a_r3_r2_r2_no_success
export P8_2_K1A_PARTIAL_GRADE=yellow_p8_2_k1a_r3_r2_r2_partial
export P8_2_K1A_STORE_ONLY_GRADE=yellow_p8_2_k1a_r3_r2_r2_store_only_no_restore
export P8_2_K1A_EVIDENCE_INCOMPLETE_GRADE=red_p8_2_k1a_r3_r2_r2_evidence_incomplete
export P8_2_K1A_RESULT_TRANSFER_AUTHORIZED=true

exec bash "${SCRIPT_DIR}/run_deepseek_p8_2_k1a_r3_simple_cpu_offload.sh" "$@"
